gravitational/gravity

lib/app/docker/runtime.go, lib/app/handler/handler.go, lib/app/suite/suite.go, lib/autoscale/aws/doc.go, lib/builder/builder.go, lib/checks/checks.go, lib/constants/constants.go, lib/schema/schema.go, lib/storage/cluster.go, lib/storage/resources.go, lib/storage/trustedcluster.go, lib/update/engine.go, lib/users/usersservice/usersservice.go, lib/utils/parse.go, tool/gravity/cli/run.go, tool/gravity/cli/status.go, tool/tele/main.go
I have tried to complete the easy parts of this:
https://github.com/gravitational/gravity.e/issues/3747
=> Tried to remove Telekube from the CLI UI

lib/ops/opsservice/instructions.go, tool/gravity/cli/input.go, tool/gravity/cli/ops.go
A few UX tweaks to the wizard install flow:
* If machine has 1 network interface, select it automatically and don't show select/confirm prompt.
* Polish/cleanup of interface selection/confirmation prompt.
* Use short versions of some flags in curl instructions.
Closes https://github.com/gravitational/gravity.e/issues/3753.
=> Autoselect the only interface in wizard flow.

docs/5.x/changelog.md
Having some issues with 5.1.1 publishing atm, but wanted to prepare changelog entry.
=> Add 5.1.1 changelog.

docs/5.x/testplan.md
Add a few more steps to the failover & resiliency test case.
=> Extend test plan resiliency scenario.

assets/rbac-app/resources/resources.yaml
Updates: https://github.com/gravitational/gravity.e/issues/3796
=> Allow coredns to list/watch pods

docs/theme/src/docs.css
=> update to docs css

docs/theme/src/docs.css, docs/theme/src/docs.js
@klizhentas same update but to gravity docs
=> more ux improvements

lib/builder/builder.go, lib/builder/syncer.go, lib/localenv/localenv.go
Backport of https://github.com/gravitational/gravity/pull/108.
=> [5.2] Fix tele build repo override.

Jenkinsfile, build.assets/robotest_run_suite.sh, lib/app/handler/handler.go, lib/app/hooks/hooks.go, lib/app/resources/decode.go, lib/app/service/manifest.go, lib/app/service/pull.go, lib/app/service/pull_test.go, lib/app/service/sync.go, lib/app/service/test/builder.go, lib/defaults/defaults.go, lib/kubernetes/drain.go, lib/pack/webpack/webpack.go, lib/rpc/deploy.go, lib/rpc/server/peer.go, lib/status/status.go, lib/storage/keyval/etcd.go, lib/storage/keyval/loginentries.go, lib/storage/keyval/permissions.go, lib/storage/storage.go, lib/update/phase_bootstrap.go, lib/utils/error.go, lib/utils/fileutils.go, lib/utils/retry.go, lib/utils/ssh.go, lib/utils/tls.go, tool/gravity/cli/gc.go, tool/gravity/cli/package.go, tool/gravity/cli/status.go, tool/gravity/cli/update.go
This PR updates the 5.2.x branch for robotesting on GCE.
It implements the same set of measures as the master to counter the intermittent 'connection reset by peer' issues observed on Google Cloud.
=> 5.2.x: sync with 5.3.x for GCE support

docs/theme/base.html, docs/theme/cta.html
@r0mant Adding cta to the bottom of all docs.
=> cta for docs footer

docs/theme/base.html, docs/theme/src/docs.css
@r0mant small update to font sizes
=> update font sizes

build.assets/Makefile, lib/expand/join.go, lib/install/flow.go, lib/install/install.go, tool/gravity/cli/install.go
Fixes https://github.com/gravitational/gravity.e/issues/3790.
=> Exit with non 0 code when interrupting a failed operation.

Jenkinsfile, Jenkinsfile.nightly, build.assets/robotest_run_nightly.sh
This PR adds nightly builds with notifications to slack if the build has failed.
The test matrix is still in a bit of a flux as I'm trying to figure out which combination does not lead to quota violations, so this is still WIP.
Requires https://github.com/gravitational/gravity.e/pull/3845.
=> Nightly builds

assets/site-app/resources/site.yaml
=> fix error in demo installer

tool/gravity/cli/upgrade.go
Closes https://github.com/gravitational/gravity.e/issues/3867.
=> Fix panic in upgrade complete.

Makefile, README.md, build.assets/Makefile
* Made it easier to configure $PATH to the latest Gravity builds
* Updated README to include public clouds
=> Minor changes to README/Makefile

web/Dockerfile, web/package-lock.json, web/package.json
Changes xtermjs version with one that has a security bug fix for CVE-2019-0542d.
=> Update xtermjs with a version that has a security fix (CVE-2019-0542d)

lib/defaults/defaults.go, lib/httplib/client.go
Forward port of https://github.com/gravitational/gravity/pull/193
=> [5.4] Fix connection leak when fetching agent report

lib/defaults/defaults.go, lib/httplib/client.go
Forward port of https://github.com/gravitational/gravity/pull/193
=> Fix connection leak when fetching agent report

assets/site-app/resources/config/teleport.yaml, lib/defaults/defaults.go, lib/ops/opsservice/configure.go, lib/process/wizard.go
Backport https://github.com/gravitational/gravity/pull/176
=> restrict teleport ciphers (#176)

docs/5.x/quickstart.md
Cleaned up "Installing via Browser" section of the quickstart.
=> More polish to the Quick Start

docs/theme/src/docs.css, package-lock.json
@r0mant Please merge when you have a change. Updated css for docs.
=> update docs css

lib/expand/join.go
Forward port of https://github.com/gravitational/gravity/pull/222
=> Avoid panic in agent

lib/expand/join.go
Forward port of https://github.com/gravitational/gravity/pull/222
=> [5.4] avoid panic in agent

docs/5.x/cluster.md
Relevant: https://github.com/gravitational/gravity.e/issues/3737#issuecomment-457650564
=> Fix resource spec inconsistency

lib/process/process.go, vendor/github.com/gravitational/teleport/lib/utils/tls.go
=> Backport: update gravity-site healthz endpoint to more reliably indicate problems

docs/5.x/changelog.md
Updates #260 
Release notes for:
- 5.5.0-alpha.8
- 5.4.6
- 5.2.8
- 5.0.29
=> release notes for cve-2019-5736

Gopkg.lock, Gopkg.toml, Makefile, build.assets/Dockerfile, vendor/github.com/gravitational/rigging/Gopkg.lock, vendor/github.com/gravitational/rigging/Gopkg.toml, vendor/github.com/gravitational/rigging/Makefile, vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go
Also bumped buildbox Go to 1.11.5.
=> Kubernetes v1.13.3.

assets/opscenter/resources/app.yaml, lib/catalog/lister.go, lib/catalog/lister_test.go
Update to e from https://github.com/gravitational/gravity.e/pull/3971.
=> Update e to fix tele login helm issue.

lib/ops/opsservice/configure.go
Discovered this issue while testing "Upgrade & Join" scenario. After upgrade Teleport nodes didn't have `gravitational.io/k8s-role` label assigned anymore which is used by various operations to query servers. With this PR:
* This label is now explicitly set from node's cluster role when configuring teleport labels. Previously I think we relied on it being present among profile labels where it was, in turn, set during "load provisioned servers" call or something like this... i.e. we relied on a side effect. Now it's set explicitly.
* Remove labels from teleport master configuration. Gravity-sites have SSH service disabled so these labels aren't needed.
=> Fix teleport labels.

docs/5.x/changelog.md
@a-palchikov Feel free to update the changelog with bugfixes that you've implemented in your giant PR, I wasn't sure about the exact list.
=> Add 5.5.0-rc.1 changelog.

docs/5.x/testplan.md
Update test plan to include scenarios for `ClusterConfiguration` and `RuntimeEnvironment` resources as well as garbage collection.
=> Update test plan with scenarios for new operations

lib/autoscale/aws/autoscaler.go, lib/autoscale/aws/autoscaler_test.go, lib/autoscale/aws/discovery.go, lib/autoscale/aws/events.go, lib/autoscale/aws/services.go, lib/defaults/defaults.go, lib/process/process.go, lib/utils/error.go
The ASG part of https://github.com/gravitational/gravity/pull/315.
=> [5.5.] Shrink ASG fixes.

lib/autoscale/aws/autoscaler.go, lib/autoscale/aws/autoscaler_test.go, lib/autoscale/aws/discovery.go, lib/autoscale/aws/events.go, lib/autoscale/aws/services.go, lib/defaults/defaults.go, lib/process/process.go, lib/utils/error.go
Forward-port of https://github.com/gravitational/gravity/pull/317.
=> Shrink ASG fixes.

lib/clients/teleport.go
Closes https://github.com/gravitational/gravity.e/issues/4003.
=> Gracefully handle incompatible auth servers.

Gopkg.lock, Gopkg.toml, assets/dns-app/hooks/Dockerfile, assets/site-app/images/hook/Dockerfile, lib/app/hooks/configure.go, lib/app/hooks/configure_test.go, lib/app/hooks/hooks_test.go, lib/app/suite/suite.go, vendor/github.com/gravitational/rigging/changeset.go, vendor/github.com/gravitational/rigging/configmap.go, vendor/github.com/gravitational/rigging/configmapgen.go, vendor/github.com/gravitational/rigging/constants.go, vendor/github.com/gravitational/rigging/deployment.go, vendor/github.com/gravitational/rigging/ds.go, vendor/github.com/gravitational/rigging/job.go, vendor/github.com/gravitational/rigging/policies.go, vendor/github.com/gravitational/rigging/rcc.go, vendor/github.com/gravitational/rigging/roles.go, vendor/github.com/gravitational/rigging/secret.go, vendor/github.com/gravitational/rigging/service.go, vendor/github.com/gravitational/rigging/serviceaccount.go, vendor/github.com/gravitational/rigging/statefulset.go, vendor/github.com/gravitational/rigging/utils.go
Requires https://github.com/gravitational/rigging/pull/58.
Updates https://github.com/gravitational/gravity.e/issues/3986.
=> Bump rigging docker reference to 5.5.2.

lib/checks/checks.go, lib/ops/opsservice/report.go, lib/report/bash.go, lib/report/k8s.go, lib/report/report.go, lib/system/fs.go, lib/system/fs_test.go, lib/system/state/state.go, lib/utils/exec.go, lib/utils/kubectl/kubectl.go, tool/gravity/cli/report.go
Updates https://github.com/gravitational/gravity.e/issues/3981.
=> [5.5] backport https://github.com/gravitational/gravity/pull/314

build.assets/Makefile, build.assets/README.md, build.assets/release.sh
Forward-port of https://github.com/gravitational/gravity/pull/329 by @kontsevoy.
=> Added more assets to the release tarball.

lib/builder/builder.go
This PR fixes the issue with tele build reporting errors like `package(gravitational.io/kubernetes:5.5.0) not found` when using a custom state directory, unless repository flag has been provided.
Since we have simplified runtime selection algorithm so it doesn't need to contact "repository" to select runtime now, tele build behavior is very straightforward now:
- Pick runtime: pinned in manifest or tele version.
- Pick cache directory: either default or specified with --state-dir.
- Verify dependencies in cache dir.
- If not met, sync deps from repository into cache dir <-- the only case when opscenter/hub is contacted
- Proceed with build.
So no more "state dir is treated as repository" nonsense, repository is always remote now:  either default (get/hub.g11l.io) or the one that's …
=> Fix state dir behavior during tele build.

lib/modules/modules.go, lib/ops/resources/gravity/gravity.go, lib/ops/resources/resources.go, tool/gravity/cli/register.go
Factor resource-specific handling from the `Modules` interface to be able to support resource handler request validation for `tele`.
Fixes https://github.com/gravitational/gravity.e/issues/4014.
=> [5.5] tele: unkown resource kind error

lib/builder/builder.go
Backport of https://github.com/gravitational/gravity/pull/334.
=> [5.5.x] Fix state dir behavior during tele build.

lib/modules/modules.go, lib/ops/resources/gravity/gravity.go, lib/ops/resources/resources.go, tool/gravity/cli/register.go
Forward port of https://github.com/gravitational/gravity/pull/337.
Requires https://github.com/gravitational/gravity.e/pull/4015.
=> Add tele-specific implementation of Resources

lib/install/phases/coredns.go
This is to fix the issue with CoreDNS crashing due to loop detection if there's a local nameserver in resolv.conf. Closes https://github.com/gravitational/gravity.e/issues/4018.
=> [5.5] Skip local nameservers from CoreDNS config.

lib/install/phases/coredns.go
Forward-port of https://github.com/gravitational/gravity/pull/345.
=> [Forward-port] Skip local nameservers from CoreDNS config.

lib/builder/build.go, lib/helm/testclient.go, lib/storage/storage.go, lib/storage/suite/suite.go, lib/users/usersservice/usersservice.go, lib/users/usersservice/usersservice_test.go
Fix a couple of low-hanging fruits:
* A typo in the tele build help output. Closes https://github.com/gravitational/gravity.e/issues/3851.
* Validate roles when inviting a new user. Closes https://github.com/gravitational/gravity.e/issues/3810.
=> Fix a couple of tele UX issues.

docs/5.x/requirements.md
We should also consider it auto-increasing it as a part of the auto-fix if it's low, there may even be a ticket about it already.
=> Add a note about inotify watch.

lib/app/acl.go, lib/app/app.go, lib/app/apps.go, lib/app/client/client.go, lib/app/handler/handler.go, lib/app/hooks/hooks.go, lib/app/hooks/hooks_test.go, lib/app/service/app.go, lib/app/suite/suite.go, lib/ops/opsservice/hooks.go, lib/ops/opsservice/status.go, tool/gravity/cli/backup_restore.go
Forward-port of https://github.com/gravitational/gravity/pull/373 to master. Closes https://github.com/gravitational/gravity.e/issues/4047.
=> Delete completed status hook pods.

docs/theme/topnav.html
For background, see gravitational/web#379
=> Update docs theme to match gravitational.com

lib/defaults/defaults.go, tool/gravity/cli/system.go
Forward-port https://github.com/gravitational/gravity/pull/382.
=> Add helm symlink on host.

tool/gravity/cli/system.go
=> remove wormhole interfaces on uninstall (#385)

lib/storage/storage.go, lib/storage/storage_test.go
Add a couple of utility methods that check for equality of servers - needed for https://github.com/gravitational/gravity.e/pull/4073.
=> Add a couple of utility methods.

docs/5.x/changelog.md
I've mentioned only the major things.
=> Add 6.0.0-beta.1 changelog.

docs/5.x/changelog.md
=> Add rc.1 changelog.

docs/5.x/changelog.md
Release notes for 5.5.9 release.
=> release notes for 5.5.9

tool/common/print.go
That's for https://github.com/gravitational/gravity.e/pull/4114.
=> Add helper method.

docs/5.x/changelog.md
Release notes related to most recent fixes for CVE-2019-1002101
=> Release notes for CVE-2019-1002101 incomplete fix

lib/install/process.go, lib/process/wizard.go, lib/update/clusterconfig/plan_test.go, lib/update/environ/plan_test.go, lib/update/internal/rollingupdate/builder.go, lib/utils/logginghook.go, tool/gravity/cli/run.go
This is a forward port of https://github.com/gravitational/gravity/pull/442.
=> Fix rolling update regression that resulting in container restart step without exec server

lib/expand/phases/elect.go, lib/install/phases/election.go, lib/ops/election.go
Forward-port of https://github.com/gravitational/gravity/pull/480, with a couple of tweaks to account for changes b/w the versions.
=> [5.5] Add retry logic to join election phase.

lib/expand/phases/elect.go, lib/install/phases/election.go, lib/ops/election.go
Forward-port of https://github.com/gravitational/gravity/pull/481. Closes https://github.com/gravitational/gravity.e/issues/3339.
=> [6.0] Add retry logic to join election phase.

lib/expand/phases/elect.go, lib/install/phases/election.go, lib/ops/election.go
I've also reduced code dupe a bit by moving out the common piece that turns on elections out of install/expand phases into a separate method.
=> [5.2] Add retry logic to join election phase.

lib/webapi/webhandler.go
closes https://github.com/gravitational/gravity.e/issues/4155
=> Preserve original URL when making redirects to login screen

docs/5.x/changelog.md
Release notes for:
* 6.0.0-rc.4
* 5.6.4
* 5.5.12
* 5.2.13
=> Release notes for 6.0.0-rc.4 5.6.4 5.5.12 5.2.13

Gopkg.lock, Gopkg.toml, vendor/github.com/gravitational/satellite/agent/proto/agentpb/timestamp.go, vendor/github.com/gravitational/satellite/monitoring/defaults_linux.go, vendor/github.com/gravitational/satellite/monitoring/dns.go, vendor/github.com/gravitational/teleport/lib/web/apiserver.go
With the fix for the logouts issue (https://github.com/gravitational/teleport/issues/2856).
Also updates satellite to 5.5.4. Closes https://github.com/gravitational/gravity.e/issues/4061.
=> Revendor teleport.

terraform-dev/Makefile, terraform-dev/install.yaml
=> Use home directory for installer

docs/6.x/monitoring.md
Found xxx placeholder on https://gravitational.com/gravity/docs/monitoring/
=> Remove xxx typo

docs/6.x/overview.md
Saw that a table was broken in overview.
=> fixed table in docs and grammar

build.assets/Makefile, lib/process/teleport.go
https://github.com/gravitational/gravity/pull/589 port to master.
=> Do not set auth gateway public addrs.

assets/telekube/resources/app.yaml, docs/6.x/requirements.md
Tested with 5.5.15, 6.0.4, 6.6.1 (backports to follow).
=> Add Ubuntu 18.04.

lib/app/pull.go
Add `SkipIfExists` flag to `tele push`. This will maintain the current behavior of skipping over existing packages (but will also skip existing applications). I'm not sure this is 100% desired but at least consistent for applications with how packages are being currently handled.
This should fix the problem with the failing publish step.
Requires https://github.com/gravitational/gravity.e/pull/4208.
=> Update 'tele push' to avoid failing on existing packages/apps

tool/gravity/cli/ops.go
My latest changes to upload code have broken the upload script that's added to the installer tarball by the somewhat dated distribution hub. This PR reverts the logic of explicitly using the gravity state directory instead of relying on the environment attribute.
=> Fix upload to work with the old (get.io provided) upload script)

lib/webapi/webapi.go, web/src/reactor.js
=> Return cluster package info when shallow flag is present

lib/schema/checks.go
Added missing kernel module ebtable_filter
=> Added missing kernel module ebtable_filter

lib/builder/build.go
Helps fix https://github.com/gravitational/gravity/issues/667 and starts to address https://github.com/gravitational/gravity/issues/664
=> Make builder create images vs snapshots

lib/expand/bootstrap.go, lib/expand/join.go, lib/schema/manifest.go, lib/schema/schema.go, tool/gravity/cli/config.go, tool/gravity/cli/register.go
https://github.com/gravitational/gravity/pull/755 backport to 6.1. Refs https://github.com/gravitational/gravity/issues/647.
=> (6.1) Add ability to specify default provider.

lib/expand/bootstrap.go, lib/expand/join.go, lib/schema/manifest.go, lib/schema/schema.go, tool/gravity/cli/config.go, tool/gravity/cli/register.go
https://github.com/gravitational/gravity/pull/755 backport to 6.2. Refs https://github.com/gravitational/gravity/issues/647.
=> (6.2) Add ability to specify default provider.

Makefile, build.assets/robotest_run_suite.sh, lib/defaults/defaults.go, lib/ops/operatoracl.go, lib/ops/ops.go, lib/ops/opsservice/configure.go, lib/ops/opsservice/packages.go, lib/ops/opsservice/plan.go, lib/ops/opsservice/shrink.go, lib/ops/opsservice/update.go, lib/process/import.go, lib/process/process.go, lib/process/process_test.go, lib/rpc/proxy/proxy.go, lib/rpc/proxy/proxy_test.go, lib/storage/plan.go, lib/update/cluster/phases/bootstrap.go, lib/update/cluster/phases/coredns.go, lib/update/cluster/phases/init.go, lib/update/cluster/phases/system.go, lib/update/cluster/plan.go, lib/update/clusterconfig/phases/update.go, lib/update/environ/phases/update.go, lib/update/system/system.go, tool/gravity/cli/update.go
Updates https://github.com/gravitational/gravity.e/issues/4230.
=> [6.0.x] forward-port the changes to fix the upgrades from 5.5.21+.

lib/install/dispatcher/buffered/dispatcher.go, lib/install/engine/interactive/wizard.go, lib/install/install.go, lib/install/utils.go, lib/rpc/server/agent_group.go, lib/rpc/server/peer.go, lib/rpc/server/peers.go, lib/utils/error.go, tool/gravity/cli/config.go, tool/gravity/cli/install.go, tool/gravity/main.go
Backport of https://github.com/gravitational/gravity/pull/746 to master.
Requires https://github.com/gravitational/gravity.e/pull/4236.
=> Provide all error context upon operation failure

docs/6.x/pack.md
Closes https://github.com/gravitational/gravity/issues/678.
=> Document manifest field that disables k8s tab.

lib/utils/cli/cli.go, lib/utils/cli/cli_test.go, tool/gravity/cli/install.go, tool/gravity/cli/utils.go, tool/gravity/cli/utils_test.go
Supporting changes for https://github.com/gravitational/gravity.e/pull/4241.
=> Add ability to add/remove flags when creating connect strategy.

lib/utils/cli/cli.go, lib/utils/cli/cli_test.go, tool/gravity/cli/install.go, tool/gravity/cli/utils.go
https://github.com/gravitational/gravity/pull/821 port.
=> (7.0) Fix license install.

lib/utils/cli/cli.go, lib/utils/cli/cli_test.go, tool/gravity/cli/install.go, tool/gravity/cli/utils.go
https://github.com/gravitational/gravity/pull/821 port.
=> (6.2) Fix license install.

lib/expand/builder.go, lib/expand/plan.go, lib/expand/plan_test.go
Temporarily remove join checks phase introduced in https://github.com/gravitational/gravity/pull/843 as it caused the issue described in https://github.com/gravitational/gravity/pull/860. Will re-introduce it once we've figured out a better way to fix it.
=> (5.5) Remove join prechecks phase.

docs/5.x/requirements.md, docs/6.x/requirements.md
Add CentOS 7.7 to the system requirements table.
=> Add centos 7.7.

lib/expand/join.go, lib/ops/opsservice/install.go, tool/tele/main.go
Updates https://github.com/gravitational/gravity.e/issues/4247.
Optionally depends on https://github.com/gravitational/gravity.e/pull/4248.
=> [6.1.x] filter out the unrelated peer on join

lib/expand/join.go, lib/ops/opsservice/install.go, tool/tele/main.go
Forward port https://github.com/gravitational/gravity/pull/885.
Fixes https://github.com/gravitational/gravity.e/issues/4247.
=> Filter out the unrelated peer on join.

lib/expand/join.go, lib/ops/opsservice/install.go, tool/tele/main.go
Forward port https://github.com/gravitational/gravity/pull/885.
Updates https://github.com/gravitational/gravity.e/issues/4247.
=> [6.2.x] filter out the unrelated peer on join.

tool/gravity/cli/run.go, tool/gravity/cli/status.go
https://github.com/gravitational/gravity/pull/891 backport.
=> (6.2) Couple of gravity cli tweaks.

tool/gravity/cli/run.go, tool/gravity/cli/status.go
https://github.com/gravitational/gravity/pull/891 backport.
=> (6.1) Couple of gravity cli tweaks.

tool/gravity/cli/run.go, tool/gravity/cli/status.go
https://github.com/gravitational/gravity/pull/891 backport.
=> (5.5) Couple of gravity cli tweaks.

lib/app/service/vendor.go, lib/app/service/vendor_test.go, tool/tele/cli/commands.go, tool/tele/cli/register.go, tool/tele/cli/run.go
https://github.com/gravitational/gravity/pull/909 backport.
=> (6.2) Pass helm values to tele build.

lib/app/service/vendor.go, lib/app/service/vendor_test.go, tool/tele/cli/commands.go, tool/tele/cli/register.go, tool/tele/cli/run.go
https://github.com/gravitational/gravity/pull/909 backport.
=> (6.1) Pass helm values to tele build.

assets/site-app/resources/site.yaml, lib/constants/constants.go
https://github.com/gravitational/gravity/pull/913 backport.
=> (6.2) Expose kubeproxy port.

assets/site-app/resources/site.yaml, lib/constants/constants.go
https://github.com/gravitational/gravity/pull/913 backport.
=> Expose kubeproxy port.

lib/install/engine/cli/cli.go
Fix gravity join command
Backport of https://github.com/gravitational/gravity/pull/932
=> Fix gravity join command (backport)

lib/install/flow.go
Fix gravity join cmd
Backport of https://github.com/gravitational/gravity/pull/932
=> Fix gravity join cmd

docs/6.x/requirements.md
Note, these are based on what I've been observing mostly when running K8s/Gravity clusters locally which can support bare Gravity installation + some headroom for running a few not CPU/RAM hungry apps.
I'm open to tweaking those if we see fit.
=> Document minimum hardware requirements.

lib/constants/constants.go, lib/ops/opsservice/endpoints.go
https://github.com/gravitational/gravity/pull/952 port.
=> (6.2) More efficient app endpoints retrieval.

lib/constants/constants.go, lib/ops/opsservice/endpoints.go
https://github.com/gravitational/gravity/pull/952 port.
=> More efficient app endpoints retrieval.

docs/6.x/changelog.md
Add 6.3.0 and deprecate 6.2.x.
=> Add 6.3.0 changelog.

lib/ops/opsservice/configure.go
Fixes a security issue where:
- master nodes re-use the same secret for a majority of certificates. Now only private keys that are required to be the same are maintained.
- Each certificate assigned to a particular node reuses the same private key. Now a private key is generated for each issued certificate.
- Rotation did not rotate private keys. Note: rotation of the root key or apiserver key is not yet supported.
=> generate separate keys for each certificate

docs/6.x/changelog.md
Release notes for 6.3.1 / 6.1.14 / 5.5.29
=> release notes for security release

docs/6.x/changelog.md
Will deploy when respective releases are published.
=> Add 6.1.15 and 6.3.2 release notes.

docs/theme/src/third-party.js
Fixes a duplicate analytics tag in the docs
https://github.com/gravitational/web/issues/696
=> remove analytics since already added with tag manager

Gopkg.lock, vendor/github.com/gravitational/teleport/CHANGELOG.md, vendor/github.com/gravitational/teleport/Gopkg.lock, vendor/github.com/gravitational/teleport/Gopkg.toml, vendor/github.com/gravitational/teleport/Makefile, vendor/github.com/gravitational/teleport/lib/auth/auth_with_roles.go, vendor/github.com/gravitational/teleport/lib/auth/permissions.go, vendor/github.com/gravitational/teleport/lib/auth/testauthority/testauthority.go, vendor/github.com/gravitational/teleport/lib/client/api.go, vendor/github.com/gravitational/teleport/lib/client/client.go, vendor/github.com/gravitational/teleport/lib/client/extensions/configurator.go, vendor/github.com/gravitational/teleport/lib/client/extensions/docker.go, vendor/github.com/gravitational/teleport/lib/client/extensions/docker_linux.go, vendor/github.com/gravitational/teleport/lib/client/extensions/helm.go, vendor/github.com/gravitational/teleport/lib/client/extensions/util.go, vendor/github.com/gravitational/teleport/lib/client/profile.go, vendor/github.com/gravitational/teleport/lib/client/weblogin.go, vendor/github.com/gravitational/teleport/lib/services/role.go, vendor/github.com/gravitational/teleport/version.go
To fix the issue accessing leaf cluster via root cluster https://github.com/gravitational/teleport/issues/3252.
=> (6.1) Revendor teleport.

assets/telekube/resources/app.yaml, docs/6.x/pack.md, docs/6.x/requirements.md
Closes https://github.com/gravitational/gravity/issues/976.
=> Add Amazon Linux 2.

web/src/cluster/services/k8s/index.js
=> Backport 6.2.x / Handle nulls in k8s APIs

web/src/cluster/services/k8s/index.js
backport https://github.com/gravitational/gravity/issues/963 fix
=> Backport  6.1.x / Handle nulls in k8s APIs 

web/src/cluster/services/k8s/index.js
=> Backport 6.3.x / handle null items returned by k8s APIs

web/shared/components/Popover/Popover.jsx
Fixes the max-height and scrollbars #624
=> Backport 6.3.x/Fix broken menu max-height and its scrollbars

lib/update/clusterconfig/clusterconfig.go, lib/update/clusterconfig/phases/restart.go, lib/update/clusterconfig/plan.go, lib/update/internal/rollingupdate/phases/elections.go, lib/update/internal/rollingupdate/phases/restart.go, lib/utils/error.go
Forward ports https://github.com/gravitational/gravity/pull/1040.
=> [6.3.x] update pod CIDR

lib/storage/smtp.go
Forward-port https://github.com/gravitational/gravity/pull/1060
=> [7.0.x] Make username/password for smtp config optional

lib/storage/smtp.go
Forward-port of https://github.com/gravitational/gravity/pull/1060
=> [6.1.x] Make username/password for smtp config optional

lib/defaults/defaults.go, lib/ops/monitoring/influxdb.go, lib/ops/monitoring/monitoring.go, lib/process/process.go
Fixes https://github.com/gravitational/gravity/issues/1073
=> Use password from secret to access InfluxDB

README.md
1. Reflecting on customer feedback
2. Announcing new features
=> My edits to Gravity README

Makefile
Bump wormhole version to use latest policy api.
=> Bump wormhole

lib/app/hooks/configure.go, lib/app/hooks/constants.go
=> [6.1.x] Add POD_IP variable in init containers

lib/app/hooks/configure.go, lib/app/hooks/constants.go
=> Add POD_IP variable in init containers

lib/log/log.go, lib/update/system/system.go, tool/gravity/cli/system.go
Backports [this](https://github.com/gravitational/gravity/pull/1033/commits/d63601d1a0dfc473071f9354ce010e64abb21329).
=> [6.3.x] backport fix for helm symlink on host

.github/CODEOWNERS
copy CODEOWNERS to each active release branch
=> create CODEOWNERS on release branch
