docs/5.x/changelog.md, docs/5.x/quickstart.md
It looks like at one point we were using a security header in release notes and then stopped. So I started using it again, but let me know if this was stopped for a reason.
=> release notes for 5.0.23 and 5.2.0-alpha.3

build.assets/robotest_run_suite.sh
To catch regressions in opscenter app installation.
Requires https://github.com/gravitational/robotest/pull/129.
Closes https://github.com/gravitational/gravity.e/issues/3738.
=> Add opscenter to robotest suite.

Makefile, tool/tele/main.go
- "make install" target adds golang flags for version/gitref
- "tele help" is more descriptive
(it's a tiny PR but I need to get it out of the way before I context-switch to another project for a couple of days)
=> Minor tweaks to CLI experience

lib/install/phases/pull.go, lib/ops/opsservice/configure.go, lib/ops/opsservice/systemupdate.go, lib/ops/opsservice/update.go, lib/pack/constants.go
Add operation-id label to each configured package and use that label during the pull phase. This makes sure only packages specific to the operation will be pulled. Fixes the install->upgrade->join scenario.
=> Pull packages by operation ID.

lib/defaults/defaults.go, lib/expand/join.go, lib/install/hook.go, lib/install/process.go, lib/rpc/deploy.go, lib/update/phase_app.go, tool/gravity/cli/config.go, tool/gravity/cli/install.go, tool/gravity/cli/rpcagent.go, tool/gravity/cli/run.go, tool/gravity/cli/update.go
This PR makes sure that `telekube-system` log file is written during automatic upgrade on the node where master agent is running. Also includes the following changes/improvements:
* Capture update hook output and write it to the system log as well, similar to what install does.
* Move default location of our log files to `/var/log` instead of the "current working dir". This gives us a stable well-known location where these files can be found, as opposed to currently having to search for them everywhere because the working dir may be completely different depending on how the command was run (e.g. if it's run via an agent, then the file will end up in / and so on).
* Do not truncate telekube-system log file every time. I think it doesn't make sense to truncate it since it oftentimes useful …
=> Write system log during upgrade.

lib/expand/join.go, lib/ops/opsservice/instructions.go
Newer versions of curl detect http2 support in the server (since we're running http/grpc on the same port) and try to upgrade connection which fails. Updates https://github.com/gravitational/gravity.e/issues/3753.
=> Force http 1.0 in install instructions.

lib/ops/opsservice/operationgroup.go, lib/ops/opsservice/service.go, lib/ops/opsservice/status.go, lib/process/process.go, lib/storage/storage.go, tool/gravity/cli/ops.go, tool/gravity/cli/status.go
This PR introduces the following changes:
* Cluster moves to degraded state if any of the nodes in the planet agent report are degraded. I've extended the existing status checker for this (the one that runs app status hook).
* Prohibit new app version upload when cluster is degraded.
* Allow shrinking degraded clusters (to be able to remove offline nodes).
This PR concludes the work started by adding disk space checkers as it makes sure that if high watermark is reached and cluster becomes degraded, new apps can't be uploaded and upgrade can't be started.
Closes https://github.com/gravitational/gravity.e/issues/3440.
Also updates https://github.com/gravitational/gravity.e/issues/3206 because with this change cluster UI now automatically shows red "with issues" state icon when a node …
=> Move cluster to degraded based on planet status.

lib/install/install.go, lib/ops/opsservice/service.go, lib/webapi/webapi.go, tool/gravity/cli/install.go
~~Delay docker setup until after `Init` to account for bootstrapping behavior of the enterprise.~~
Move merging of docker configuration during install to `CreateSite` API.
Requires https://github.com/gravitational/gravity.e/pull/3756.
=> Delay docker setup during install

docs/5.x/testplan.md
Add two more scenarios to the test plan:
- failover
- tele build (oss and enterprise)
- licensing & encryption (enterprise)
=> Update test plan.

Makefile
... so Gravity's documentation workflow is now 100% identical to Teleport's
=> Added run-docs Make target

lib/install/hook.go, lib/ops/opsservice/shrink.go, tool/gravity/cli/run.go
Fixes the `Failed to fire hook: open /var/lib/gravity/var/log/telekube-system.log: no such file or directory` issue for shrink agent. Related to https://github.com/gravitational/gravity.e/issues/3761.
Also add "wizard" command to the list of commands that write to /var/log/telekube-system.log too (forgot to add it originally), otherwise it only writes to journald.
Also closes https://github.com/gravitational/gravity.e/issues/3763.
=> Use default system log for shrink agent.

Makefile, build.assets/Makefile, lib/app/resources/decode.go, lib/app/resources/decode_test.go, lib/app/resources/resourcefiles.go, lib/app/resources/utils.go, lib/app/service/vendor.go, lib/constants/constants.go, lib/install/hook.go, lib/schema/extensions.go, lib/utils/retry.go
Closes https://github.com/gravitational/gravity.e/issues/3764.
Also this PR accumulated a couple of other small fixes:
* Fix year short date format (I used hours instead of year by mistake).
* Fix default build target to remove buildbox b/c it breaks the build on Mac (where bins are built on host).
* Fix issue with infinite logging recursion when invoking gravity install without sudo.
=> Skip unrecognized objects during vendoring.

lib/app/docker/imageservice.go, lib/vacuum/prune/pack/pack.go, lib/vacuum/prune/pack/pack_test.go, lib/vacuum/prune/registry/registry.go
This fixes an issue with the package pruner that would delete legacy planet packages regardless of whether they're used.
This was not caught before as the name of the planet package changed and legacy packages were deleted unconditionally.
Now that we want to reuse (some) garbage collection functionality on older clusters, this should be changed.
=> gravity gc: do not remove required packages

assets/kubernetes/resources/app.yaml, lib/app/dependency.go, lib/loc/loc.go, lib/loc/loc_test.go, lib/schema/manifest.go
Add planet package to package dependencies to keep compatibility with older versions.
This will allow older versions to correctly pull the package when building an installer.
Newer versions will ignore the dependency (as it was moved elsewhere).
As a side effect, (application) packages as provided in the application manifest are deduplicated.
Fixes https://github.com/gravitational/gravity.e/issues/3768
=> Add planet package to package dependencies

tool/gravity/cli/gc.go
Account for older clusters with not explicitly completed update operation when determining if package pruning can be performed using `system gc package`.
This also matches the behavior of `lib/ops/opsservice#operationGroup.canCreateOperation`.
=> Use cluster state to determine ability to prune packages for the low-level command

lib/expand/join.go, lib/install/phases/pull.go, lib/ops/opsservice/operationgroup.go
* Fix an issue with installing AWS cluster via Ops Center.
* Fix an issue with runtime package not being marked as such during pull phase.
* Add a bit more debug info to the operation group to confirm the expand failure theory from https://github.com/gravitational/gravity.e/issues/3773 if it happens again.
Update: Despite robotest succeeding, it actually failed resize scenario in the same fashion as described in https://github.com/gravitational/gravity.e/issues/3773. My last commit here added more debug info for this scenario so let's see if it fails again.
Update 2: And of course with debug info turned on, the test succeeded :)
=> Fix a couple of issues.

build.assets/robotest_run_suite.sh
I did not extend the testing matrix - just swapped redhat 7.4 with 7.5 and centos 7.4 with 7.5 at certain places to keep the matrix manageable - let me know if extending actually makes sense.
Fixes https://github.com/gravitational/gravity.e/issues/3427.
=> CentOS/RedHat 7.5

lib/app/service/docker.go, lib/app/service/vendor.go
If the image used in Helm chart includes registry address, then it won't be stripped when pushing images to local registry leading to issues like:
```
INFO             Tagging localhost:5000/confluentinc/cp-kafka:5.0.0 with opts={127.0.0.1:38001/localhost:5000/confluentinc/cp-kafka 5.0.0 true}. export-directory:/tmp/vendor390533500 service/docker.go:124
```
This PR changes image parsing during push to use our `loc.ParseDockerImage()` method that strips registries.
Also add a bit more detailed logging for vendoring.
=> Strip original registry when tagging images to local registry.

lib/app/service/docker.go, lib/app/service/vendor.go
Backport of https://github.com/gravitational/gravity/pull/72.
=> Strip original registry when tagging images to local registry (5.2.x backport).

lib/rpc/server/peers.go
Otherwise just a generic "RPC agent couldn't connect" error is displayed to a user. Closes https://github.com/gravitational/gravity.e/issues/3791.
=> Show joining agent error details.

lib/webapi/webhandler.go, web/devServer.js, web/src/app/config.js, web/src/app/index.jsx, web/src/app/modules/installer/components/progress/main.jsx
Instead of redirecting to last installation step (bandwagon app), redirect a user back to installer if last installation step has not been completed.
The installer in this case will show that installation has been completed and ask a user to click a button to complete the installation.
Also fixes https://github.com/gravitational/gravity.e/issues/3781
=> better handling of redirects to install complete step

lib/builder/builder.go, lib/builder/syncer.go, lib/localenv/localenv.go
During one of recent refactorings a change was made that if `--state-dir` flag is explicitly provided to the tele build command, it is always used as a package source (which is used for building installer from pre-built state). However, some customers use `--state-dir` to store login information (`tele login --state-dir=...`) and still want to download packages from their Ops Center.
This PR restores the original behavior that if `--repository` flag is provided alongside `--state-dir`, then this repository is used as a package source.
Closes https://github.com/gravitational/gravity.e/issues/3816.
=> Fix tele build repo override.

lib/expand/builder.go, lib/expand/fsm.go, lib/expand/fsmspec.go, lib/expand/join.go, lib/expand/plan_test.go, lib/fsm/fsm.go, lib/fsm/logger.go, lib/install/flow.go, lib/install/fsm.go, lib/install/fsmspec.go, lib/install/install.go, lib/install/phases/bootstrap.go, lib/install/phases/postsystem.go, lib/install/plan.go, lib/install/plan_test.go, lib/install/planbuilder.go, lib/localenv/clusterenv.go, lib/ops/opsservice/shrink.go, lib/ops/opsservice/status.go, lib/rpc/server/agent_group_test.go, lib/status/status.go, lib/storage/plan.go, tool/gravity/cli/install.go, tool/gravity/cli/ops.go, tool/gravity/cli/planet.go, tool/gravity/cli/run.go, tool/gravity/cli/status.go, tool/gravity/cli/utils.go
Backports #91 to 5.2.x
Requires https://github.com/gravitational/gravity.e/pull/3822.
Updates gravitational/gravity.e#3770.
=> Backport of #91 to 5.2.x

lib/app/service/docker.go, lib/app/service/docker_test.go, lib/app/service/vendor.go, lib/app/service/vendor_test.go
Fixes https://github.com/gravitational/gravity.e/issues/3828.
=> Split domain on host/port when parsing docker image reference.

lib/app/service/docker.go, lib/app/service/docker_test.go, lib/app/service/vendor.go, lib/app/service/vendor_test.go
Fixes https://github.com/gravitational/gravity.e/issues/3828.
=> [5.3] split domain on host/port when parsing docker image reference.

lib/app/service/docker.go, lib/app/service/docker_test.go, lib/app/service/vendor.go, lib/app/service/vendor_test.go
Fixes https://github.com/gravitational/gravity.e/issues/3828.
=> [5.2] split domain on host/port when parsing docker image reference.

lib/update/plan.go
Fetch existing DNS from runtime configuration unconditionally - this will allow to counteract rouge values in DB if it gets messed up (i.e. by running previous version with a bug or similar).
=> [5.2] fetch existing DNS from runtime configuration unconditionally

tool/gravity/cli/upgrade.go
Backport https://github.com/gravitational/gravity/pull/151.
=> [5.3.x] Fix panic in upgrade complete.

tool/gravity/cli/upgrade.go
Backport https://github.com/gravitational/gravity/pull/151.
=> [5.4.x] Fix panic in upgrade complete.

tool/gravity/cli/upgrade.go
Backport https://github.com/gravitational/gravity/pull/151.
=> [5.2.x] Fix panic in upgrade complete.

lib/storage/plan.go, lib/update/phase_kubernetes.go, lib/vacuum/internal/fsm/builder.go, lib/vacuum/internal/fsm/builder_test.go, lib/vacuum/internal/fsm/engine.go, lib/vacuum/internal/phases/journal.go, lib/vacuum/internal/phases/packages.go, lib/vacuum/internal/phases/registry.go, lib/vacuum/plan.go, lib/vacuum/prune/journal/journal.go, lib/vacuum/prune/pack/pack.go, lib/vacuum/prune/pack/pack_test.go, lib/vacuum/prune/pruner.go, lib/vacuum/prune/registry/registry.go, lib/vacuum/vacuum.go, tool/gravity/cli/gc.go, tool/gravity/cli/run.go
Fetch remote applications upon initializing the `gc` operation and store in operation plan.
Updates https://github.com/gravitational/gravity.e/issues/3878.
=> [5.3] gc: store additional operation state on plan init

build.assets/Makefile
Otherwise container builds are not entirely reproducible cause they depend on the host's cache.
=>  Remove gocache directory mount from build container.

tool/gravity/cli/system.go
Otherwise reusing the same node fails unless the cni0 interface is deleted manually.
=> Remove cni interface in system uninstall.

lib/modules/modules.go, lib/ops/opshandler/resources.go, lib/ops/resources/gravity/gravity.go, lib/ops/resources/resources.go, lib/storage/resources.go, tool/gravity/cli/environ.go, tool/gravity/cli/register.go, tool/gravity/cli/resources.go
* Handle alternative resource names in modules interface.
* Make 'name' flag optional for 'gravity resource rm'
* Fix typo in a message banner
Complimentary PR: https://github.com/gravitational/gravity.e/pull/3903
=> [5.3]: fix a typo and make `name` optional in `gravity resource rm`

docs/5.x/pack.md, lib/schema/manifest.go
Use overlay as the default storage driver. I don't know if overlay2 would be a better default, or if overlay is more likely to support a wider range of systems.
Updates https://github.com/gravitational/gravity/issues/211
Updates https://github.com/gravitational/gravity.e/issues/3913
Requires backport to 5.3.x/5.4.x.
=> Set overlay driver as default in application manifest

lib/expand/join.go
If an interface is used, the it becomes trickier to deal with empty vs nil interface here:
```go
// Since getAgent returns a pointer, and if it's a nil, p.agent will be
// set to (*rpserver.PeerServer(nil), nil) as the interface
// value which makes p.agent != nil
p.agent, err = p.getAgent(*ctx)
if err != nil {
return trace.Wrap(err)
}
```
Updates https://github.com/gravitational/gravity.e/issues/3916.
=> [5.3] avoid panic in agent

docs/5.x/changelog.md, docs/5.x/cli.md, docs/5.x/cluster.md, docs/5.x/guides.md, docs/5.x/installation.md, docs/5.x/instance.md, docs/5.x/manage.md, docs/5.x/monitoring.md, docs/5.x/opscenter.md, docs/5.x/overview.md, docs/5.x/pack.md, docs/5.x/quickstart.md, docs/5.x/requirements.md, docs/5.x/terraform.md, docs/5.x/workshops.md
Also ran everything through a spellchecker, hence multiple typos fixed.
I will update the upgrade section (remove mostly as it now duplicates information from the new `Managing an ongoing Operation` section that describes the updated `gravity plan`) once I've forward ported the `runtime_environment` implementation.
I also feel that all operation-related content should probably go into a separate file, like `operations.md`.
=> Update docs on `runtimeenvironment` resource, 'gravity plan'

lib/app/resources/decode.go, lib/app/resources/decode_test.go, lib/app/resources/resourcefiles.go, lib/app/resources/resourcefiles_test.go, lib/app/resources/utils.go, lib/app/service/vendor.go
Do not filter unrecognized resources - instead, pass them through as `Unknown`s.
Fixes https://github.com/gravitational/gravity.e/issues/3923.
=> Do not filter unrecognized resources

docs/5.x/pack.md, lib/schema/manifest.go
Backport: https://github.com/gravitational/gravity/pull/212
* Set overlay driver as default in application manifest
https://github.com/gravitational/gravity/issues/211
https://github.com/gravitational/gravity.e/issues/3913
* use overlay2 as the default
* minimize the note about device mapper support
* minimize the note about device mapper support
=> Set overlay driver as default in application manifest (#212)

lib/expand/join.go, lib/install/flow.go, lib/install/install.go, lib/localenv/clusterenv.go, lib/modules/modules.go, lib/ops/agents.go, lib/ops/agents_test.go, lib/ops/opsservice/endpoints.go, lib/ops/opsservice/service.go, lib/status/status.go, lib/utils/parse.go, lib/utils/parse_test.go, tool/gravity/cli/status.go
This PR implements a number of UX improvements for the installer, mostly cosmetic stuff:
* When installing a multi-node flavor, installer outputs a table with required join commands that should be run on other nodes. (And re-prints the table every time a new node joins/leaves).
* In a multi-node install scenario, previously when you specified incorrect "role" to the join command, it would just spin until timeout. I've now made it exit with appropriate error message immediately.
* If a customer specified `--token` to the install command, the same token becomes the join token.
* Extend status command to collect cluster/application endpoints information and print it after successful installation as well as in `gravity status`.
* Added some post-install messages, adjusted colors to make some …
=> Installer UX.

assets/site-app/images/hook/entrypoint.sh, assets/site-app/images/site/init.sh, assets/site-app/resources/monitoring.yaml, assets/site-app/resources/site.yaml, lib/defaults/defaults.go, lib/install/planbuilder.go, lib/schema/manifest.go, lib/schema/manifest_test.go, lib/schema/schema.go, lib/update/plan.go
This PR allows to exclude certain applications (logging/monitoring/tiller) from installation. It is controller by their respective "extensions" field in the manifest. We already had it for logs and monitoring but it only affected UI tabs display - now it also skips respective system apps during install/upgrade. I also added a "catalog" field to it which does the same for tiller app. Closes https://github.com/gravitational/gravity.e/issues/3928.
Note: I had to move monitoring-related rbac resources out of site.yaml and create them separately b/c there may be no monitoring namespace anymore (if monitoring app is excluded).
=> Allow excluding certain applications from install.

lib/process/process.go, vendor/github.com/gravitational/teleport/lib/utils/tls.go
Updates healthz processing, so that:
- Generate a timeout if the backend is slow/unresponsive instead of waiting until the client has timed out
- Log slow backend requests
- Removed sending raw backend error messages to clients (this endpoint allows unauthenticated access)
Extra:
- Set server cipher selection, to avoid a bug that's tripped me up a couple times, where the curl in planet can't communicate using http2 to the gravity-site server
- Update cipher selection to be stricter recommendations, using teleport defaults
=> update gravity-site healthz endpoint to more reliably indicate problems

assets/site-app/resources/site.yaml, docs/5.x/cluster.md, lib/constants/constants.go, lib/kubernetes/pods.go, lib/ops/operatoracl.go, lib/ops/ops.go, lib/ops/opsclient/opsclient.go, lib/ops/opshandler/opshandler.go, lib/ops/opshandler/resources.go, lib/ops/opsroute/forward.go, lib/ops/opsservice/authgateway.go, lib/ops/opsservice/configure.go, lib/ops/opsservice/monitoring.go, lib/ops/resources/gravity/collection.go, lib/ops/resources/gravity/gravity.go, lib/process/process.go, lib/process/process_test.go, lib/process/teleport.go, lib/process/watch.go, lib/processconfig/merge.go, lib/storage/authgateway.go, lib/storage/authgateway_test.go, lib/storage/cluster_test.go, lib/storage/resources.go, lib/utils/parse.go, lib/utils/parse_test.go, lib/utils/stringset.go, lib/utils/stringset_test.go, lib/utils/units.go
This PR adds support for the `authgateway` resource which basically allows to tweak various configuration parameters of embedded Teleport.
I have removed documentation for the `cluster_auth_preference` resource because it is obsoleted by auth gateway. The actual resource support is still there for backward compatibility (and prints a warning when used).
Closes https://github.com/gravitational/gravity.e/issues/3918.
=> AuthGateway resource.

Makefile, assets/telekube/resources/app.yaml, lib/app/app.go, lib/builder/build.go, lib/builder/builder.go, lib/catalog/lister.go, lib/catalog/lister_test.go, lib/constants/constants.go, lib/hub/hub.go, lib/loc/loc.go, lib/loc/make.go, lib/ops/cluster.go, lib/ops/opsservice/service.go, lib/schema/constants.go, lib/schema/manifest.go, lib/schema/parse.go, lib/schema/schema.go, tool/gravity/cli/config.go, tool/gravity/cli/update.go, tool/tele/cli/commands.go, tool/tele/cli/ls.go, tool/tele/cli/pull.go, tool/tele/cli/register.go, tool/tele/cli/run.go
This PR implements most of UX improvements for tele from https://github.com/gravitational/gravity.e/issues/3911. The next big chunk of work that will have to be done before that ticket could be closed will be migrating OSS hub to become a chart repository and teaching tele to work with it, but I wanted to merge these smaller fixes/improvements now. Here's the gist:
* When building telekube-app, add description that includes Kubernetes version (propagated from makefile).
* Add support for `baseImage` manifest field. This is basically the same as `systemOptions.runtime` but the future docs will be referring to base image instead.
* Multiple `tele ls` behavior and UX tweaks:
- Move common parts of code to an interface shared by OSS/enterprise so we don't have to reimplement stuff anymore.
- …
=> Tele CLI/UX improvements.

lib/builder/build.go, lib/builder/builder.go, lib/builder/builder_test.go, lib/builder/syncer.go, lib/catalog/lister.go, lib/pack/utils.go
This PR changes the way tele picks runtime (base image) version when it's not explicitly pinned in the manifest.
* When runtime is not pinned, tele defaults to its own version. It ensures 100% compatibility. See the linked ticket for more reasonings/benefits of this approach.
* When runtime is pinned, it is used as before, but compatibility check has become a bit more strict - in addition to having equal maj/min semver components, tele should be >= runtime version.
Closes https://github.com/gravitational/gravity.e/issues/3969.
=> Default to tele version when selecting runtime.

docs/5.x/testplan.md, lib/ops/opsservice/configure.go, lib/ops/opsservice/plan.go, lib/ops/opsservice/update.go, lib/storage/storage.go
Previously teleport nodes were using a single master node as their auth server so if that node went down, all teleport nodes would effectively be rendered useless as they wouldn't be able to register. With this PR:
* Teleport nodes on masters prefer their local auth server and fallback to other masters.
* Teleport nodes on regular nodes use auth servers on masters.
=> Improve teleport nodes resiliency.

assets/telekube/resources/clusterDeprovision.yaml, assets/telekube/resources/clusterProvision.yaml, assets/telekube/resources/nodesDeprovision.yaml, assets/telekube/resources/nodesProvision.yaml, lib/defaults/defaults.go, lib/ops/opsservice/install.go
This PR implements a few fixes for the use-case of installing a cluster on AWS using automatic provisioner via Ops Center:
* Launch provisioning hooks in `kube-system` namespace because gravity-site doesn't have access to `default` anymore.
* Update default VPC CIDR range to match provisioner: https://github.com/gravitational/provisioner/blob/master/provider/awsutil/vpc.go#L13. It used to be 10.100/16, but apparently got changed so gravity was picking conflicting subnets.
=> Fix AWS install.

lib/storage/keyval/users.go
Ignore not found errors when iterating over users. Otherwise it causes issues with expiring SSO users.
=> Fix an issue with expiring users.

lib/storage/plan.go, lib/vacuum/internal/fsm/builder.go, lib/vacuum/internal/fsm/builder_test.go, lib/vacuum/internal/fsm/engine.go, lib/vacuum/internal/phases/journal.go, lib/vacuum/internal/phases/packages.go, lib/vacuum/internal/phases/registry.go, lib/vacuum/plan.go, lib/vacuum/prune/journal/journal.go, lib/vacuum/prune/pack/pack.go, lib/vacuum/prune/pack/pack_test.go, lib/vacuum/prune/pruner.go, lib/vacuum/prune/registry/registry.go, lib/vacuum/vacuum.go, tool/gravity/cli/gc.go, tool/gravity/cli/run.go
Backport [fix](https://github.com/gravitational/gravity/pull/171)  to `gravity gc` to enable package collection on regular nodes.
Fixes https://github.com/gravitational/gravity.e/issues/3878.
=> [5.2] backport package collection fix

docs/5.x/cluster.md, docs/5.x/manage.md
Our role example specs in the documentation were obsolete (v2) and/or incorrect. This PR updates them to v3 and adds missing permissions so they are copy-pasteable now.
=> Update role specs in the docs.

lib/helm/client.go, tool/gravity/cli/commands.go, tool/gravity/cli/helm.go, tool/gravity/cli/register.go, tool/gravity/cli/run.go
Made a couple of adjustments to the `gravity app ls` command while playing with the application catalog:
* Add `list` alias for the command.
* Include additional release statuses in default output (to be able to see releases that are being installed/uninstalled/upgraded/etc. - will be needed for the dashboard too).
* Add `--all` flag to the command to display releases with all possible statuses (including "deleted", "superseded", etc. which you normally don't need to see).
=> App list command tweaks.

lib/install/phases/connect.go, lib/ops/opsservice/shrink.go, lib/ops/opsservice/teleport.go, lib/process/process.go
This PR improves the way the "master" server runner is chosen during shrink operation. It makes sure that if the node that's being removed is master, it can't be chosen as a master runner. Previously, the code would choose any master node which had a decent chance of choosing the node that's being removed which could lead to all sorts of issues. Closes https://github.com/gravitational/gravity.e/issues/3740.
While testing, I have also observed that when installing a 3-node cluster, the two non-leader gravity-site processes would not initialize properly with error `failed to find any peer with hash(964ae66380e9b7cfadb9752193aafe8aea7596819bfad0ae302315a9fac8f763), failed to load RPC credentials` so I added retry to RPC credentials initialization and made sure it fixes the issue.
=> Fixes for shrink and process.

lib/expand/phases/elect.go, lib/status/status.go, tool/gravity/cli/status.go
Fetch application endpoints using the actual cluster operator client to avoid kubeconfig errors on regular nodes. This fixes the issue with `gravity status` always returning `degraded` for cluster status on regular (non-master) nodes.
Updates https://github.com/gravitational/gravity.e/issues/3991.
=> Query application endpoints from cluster controller

docs/5.x/changelog.md
Weirdly, 5.3.x was gone from the releases table for some reason, I added it back.
=> Add 5.2.11 and 5.3.9 release notes.

docs/5.x/changelog.md
To be merged / deployed after 5.5.0 is cut.
=> Add 5.5.0 changelog.

Makefile, lib/autoscale/aws/autoscaler.go, lib/autoscale/aws/autoscaler_test.go, lib/autoscale/aws/discovery.go, lib/autoscale/aws/events.go, lib/autoscale/aws/services.go, lib/defaults/defaults.go, lib/ops/opsservice/shrink.go, lib/ops/opsservice/teleport.go, lib/process/process.go, lib/utils/error.go
This PR implements a number of improvements for shrink operation:
* In ASG use-case, wait for the instance to terminate before launching shrink. Closes https://github.com/gravitational/gravity.e/issues/3992.
* Make sure that only gravity-site leader monitors ASG events. Previously all of them monitored it which caused multiple shrink operation to start.
* Backport https://github.com/gravitational/gravity/pull/301 to prevent shrink from running commands on the leaving node.
=> [5.4.x] Shrink (incl. ASG) fixes & improvements.

lib/checks/checks.go, lib/ops/opsservice/report.go, lib/report/bash.go, lib/report/k8s.go, lib/report/report.go, lib/system/fs.go, lib/system/fs_test.go, lib/system/state/state.go, lib/utils/exec.go, lib/utils/kubectl/kubectl.go, tool/gravity/cli/report.go
Also, update runner to universally accept context.
Fixes https://github.com/gravitational/gravity.e/issues/3981.
=> Do not stream stderr to the report tarball

docs/5.x/cluster.md, docs/5.x/overview.md
An update of https://github.com/gravitational/gravity/pull/93
=> (docs) rename Telekube -> Gravity + introduce opscenter earlier

docs/5.x/changelog.md
@a-palchikov I wasn't sure if https://github.com/gravitational/gravity.e/issues/3986 was worth mentioning in the changelog, or the best way to describe it in customer-friendly terms. Lmk if you think it should be included.
=> Add 5.5.1 changelog.

docs/5.x/changelog.md
I also noticed that commas in the dates were messed up.
Also updated EOL date for 5.5 in accordance with our new LTS policy.
=> Add 5.0.30 changelog.

Gopkg.lock, vendor/github.com/gravitational/teleport/lib/auth/init.go, vendor/github.com/gravitational/teleport/lib/services/role.go, vendor/github.com/gravitational/teleport/lib/web/apiserver.go
This is to include a new Teleport's new web API method for searching audit events implemented in https://github.com/gravitational/teleport/pull/2632. Closes https://github.com/gravitational/gravity.e/issues/4019.
=> Update vendored teleport.

lib/app/acl.go, lib/app/app.go, lib/app/apps.go, lib/app/client/client.go, lib/app/handler/handler.go, lib/app/hooks/hooks.go, lib/app/hooks/hooks_test.go, lib/app/service/app.go, lib/app/suite/suite.go, lib/ops/opsservice/hooks.go, lib/ops/opsservice/status.go, tool/gravity/cli/backup_restore.go
By default deleting a job does not delete its dependent pod which in our case leads to accumulation of completed pods of status hooks. This PR specifies appropriate propagation policy so status hook pods are also deleted. Refs https://github.com/gravitational/gravity.e/issues/4047.
=> [5.5] Delete completed status hook pods.

lib/defaults/defaults.go, lib/ops/operatoracl.go, lib/ops/ops.go, lib/ops/opsclient/opsclient.go, lib/ops/opshandler/opshandler.go, lib/ops/opsroute/forward.go, lib/ops/opsservice/service.go, lib/ops/opsservice/users.go, lib/process/process.go, lib/process/teleport.go, lib/storage/resources.go, lib/utils/parse.go, lib/webapi/clusterinfo.go, lib/webapi/webapi.go, tool/gravity/cli/user.go
This PR implements a few changes in web API needed to power the new dashboard:
* Add a new "cluster info" web API method that returns basic cluster information such as public/internal endpoints.
* The bulk of the changes is making handlers that previously always used local cluster services (such as update user, create invite, etc.) to be routed to remote clusters when necessary. This required adding those methods to the operator service so router can be used. Note: I kept old web handlers for compatibility so current UI continues to work, will remove them once we're fully migrated to the new UI.
* Other minor things, such as including user's "bundle" in a list of application releases so it is displayed in the table with other apps too.
Closes …
=> Update webapi for new dashboard.

lib/ops/operatoracl.go, lib/ops/ops.go, lib/ops/opsclient/opsclient.go, lib/ops/opshandler/resources.go, lib/ops/opsroute/forward.go, lib/ops/opsservice/releases.go, lib/ops/opsservice/releases_test.go, lib/storage/release.go, lib/utils/parse.go, lib/webapi/webapi.go
A few updates to web API for the new dashboard:
* Return information about installed app releases in `/sites` and `/sites/<clustername>` handlers.
* Add `shallow` flag to the aforementioned methods which, if set to true, makes them return stripped down cluster objects which UI does not always need (saving traffic / increasing performance during polling).
* Remove standalone `/releases` web API method cause they are available as a part of web cluster object now.
=> Web API updates.

lib/install/phases/resources.go, lib/ops/operatoracl.go, lib/ops/ops.go, lib/ops/opshandler/resources.go, lib/ops/resources/gravity/gravity.go, lib/ops/resources/gravity/gravity_test.go, lib/ops/resources/resources.go, lib/ops/resources/resources_test.go, lib/webapi/resources.go, tool/gravity/cli/resources.go
This PR enhances resource controller to support routing requests for creating/listing/deleting resources to remote clusters. Previously, resource controller only worked with the local cluster, which does not work for us anymore because the new dashboard needs to be able to manage certain resources on remote clusters (in the Ops Center use-case). Thus, `(Create|List|Delete)Resource` requests now have a `SiteKey` so requests get routed to appropriate cluster using existing opsrouters machinery, instead of always being routed to the local cluster.
Also, tweak acl rules a bit so the remote agent can manage users/roles/authconnectors for remote clusters.
Refs https://github.com/gravitational/gravity.e/issues/4071.
=> Make resource controller cluster-aware.

README.md
... in preparation for 6.0 launch
=> Rename "bundle" to "image" in README

Gopkg.lock, assets/site-app/resources/site.yaml, lib/ops/endpoints.go, lib/ops/endpoints_test.go, lib/ops/opsservice/endpoints.go, lib/process/process.go, lib/process/teleport.go, lib/status/status.go, lib/storage/authgateway.go, lib/utils/parse.go, lib/webapi/clusterinfo.go, tool/gravity/cli/status.go, vendor/github.com/gravitational/teleport/lib/kube/proxy/forwarder.go
This PR addresses a few issues with Kubernetes proxy that appeared after upgrading to Teleport 3.2. Teleport starting from 3.2 uses Kubernetes Impersonation API instead of CSR API.
* Revendor latest Teleport to address a bug related to sending empty auth information to API server.
* Update gravity-site RBAC to allow impersonation requests.
* Fix a couple of issues with `tsh login` - e.g. it now expects Teleport proxy to returns "proxy settings" which gravity-site wasn't returning before.
Plus a couple of general fixes:
* Factor out the logic for assembling "cluster endpoints" (auth gateway address and UI) to a common method which is now used by both gravity status and new UI so they display consistent info.
* A couple of tweaks to gravity status output.
=> Kubernetes proxy fixes.

lib/ops/monitoring/metrics.go
If requested interval was less than an hour, the code would pass it as a fraction of an hour which Prometheus API would not understand. This changes it to minutes.
=> Fix an issue with metrics API.

lib/ops/monitoring/metrics.go
One more tweak to the metrics API. Previously, when Prometheus would return an empty data set for some range query, the code would return an error. This PR changes this behavior by returning an empty series in this case.
=> Do not return error for empty series.

lib/defaults/defaults.go, lib/webapi/webapi.go, lib/webapi/webhandler.go
* Update name of the file for installer tarball generated by web API. It was obsolete (still used ".tar.gz" extension) and not user-friendly (included repo name for example). Now it's `name-version.tar`. Needed by the new dashboard.
* Also tweak web display name for our internal apps (gravity/opscenter) a bit.
=> Couple UX tweaks.

lib/catalog/lister.go, lib/constants/constants.go, lib/hub/hub.go, lib/ops/opsroute/forward.go, tool/tele/cli/pull.go
This is similar to what we did to `telekube`/`gravity` - make tele show `hub` instead of `opscenter`.
Also, use remote operator client when retrieving auth gateway. This fixes install via UI wizard (otherwise it shows internal error after completing install and trying to show the cluster).
@a-palchikov @knisbet We can cut `6.0.0-rc.1` after this (and its enterprise counterpart) is merged.
=> Rename opscenter to hub in tele output.

lib/webapi/resources.go, lib/webapi/webapi.go
I kept them for compatibility with the old UI but now that the new UI has been merged, we can get rid of them.
=> Remove obsolete webapi handlers.

tool/gravity/cli/config.go
Otherwise, if a too short token is provided, teleport silently fails to initialize (which probably should be fixed on its own later too to propagate errors to the client). Closes https://github.com/gravitational/gravity.e/issues/4112.
=> Check token length.

assets/telekube/resources/app.yaml
I've spun up a RHEL 8 instance on EC2, installed a cluster successfully and clicked through the UI tabs, seems to be working. Ideally, we'll need to add it to robotest too.
Note, CentOS 8 is not out yet.
Closes https://github.com/gravitational/gravity.e/issues/4081.
=> Add rhel 8 to supported distros.

lib/webapi/connect.go
I've tested this with both standalone cluster and via hub. Closes https://github.com/gravitational/gravity.e/issues/4098.
=> Query pod/container before initiating ssh session.

lib/install/process.go, lib/process/wizard.go, lib/update/clusterconfig/plan_test.go, lib/update/environ/plan_test.go, lib/update/internal/rollingupdate/builder.go, lib/utils/logginghook.go, tool/gravity/cli/run.go
* Fix a regression with rolling update with restart not configured to happen on the target node.
* Configure resource create/remove operations to log similar to install operation - both to `syslog` and a log file.
=> [5.5] fix restart regression

lib/ops/ops.go, lib/ops/opsservice/agents.go, lib/ops/opsservice/runner.go, lib/system/environ/validate.go, lib/utils/progress.go
Provide a non-logging Exec API in the agent service to use for debug report collection to silence the output of stdout.
Fixes https://github.com/gravitational/gravity.e/issues/4144.
=> Do not log binary output of remote report collect call

lib/expand/join.go, lib/install/install.go, lib/install/operation.go, tool/gravity/cli/clusterupdate.go, tool/gravity/cli/install.go
Currently, service does not handle at least `SIGTERM` to gracefully shutdown and instead is killed by the system as a result. I was mistakenly believing I could not use interrupt signals to properly shutdown just the service.
This PR handles server interrupts (`SIGTERM`/`SIGQUIT`) gracefully - without invoking abort mechanism of the client.
=> Handle server interrupt gracefully - without invoking abort mechanism

Gopkg.lock, Gopkg.toml, lib/constants/constants.go, lib/expand/join.go, lib/fsm/fsm.go, lib/install/flow.go, lib/update/cluster/automatic.go, lib/update/cluster/builder.go, lib/update/cluster/builder_test.go, lib/update/cluster/plan.go, lib/update/updater.go, lib/vacuum/vacuum.go, tool/gravity/cli/clusterconfig.go, tool/gravity/cli/clusterupdate.go, tool/gravity/cli/commands.go, tool/gravity/cli/environ.go, tool/gravity/cli/gc.go, tool/gravity/cli/install.go, tool/gravity/cli/plan.go, tool/gravity/cli/register.go, tool/gravity/cli/run.go, tool/gravity/cli/update.go, vendor/github.com/gravitational/trace/log.go, vendor/github.com/gravitational/trace/trace.go, vendor/github.com/gravitational/trace/udphook.go
* resuming operation should not use --force - otherwise even completed phases are re-executed. Instead, introduce a special implicit resume flag for this purpose.
* update operation plan might be broken if leader node is not first in the list of master nodes (https://github.com/gravitational/gravity.e/issues/4138).
* run the update operation controller on the same node where the operation was started.
* revert the blocking by default mode for update (introduced 
Also updates trace to 1.1.7 as `e/version/5.5.x` would have otherwise been incompatible.
Requires https://github.com/gravitational/gravity.e/pull/4145.
=> [5.5.x] backport a few bugfixes

lib/checks/checks.go
Original [PR](https://github.com/gravitational/gravity/pull/451):
```
Kubernetes by default has the range of 30000-32767 for `NodePort` assignment. However, it is not appropriate to ensure (and fail the install) if something is bound within this range, because Kubernetes will actually only choose open ports when assigning a `NodePort`. Additionally, this range can be changed via configuration, so hardcoding verification of it being unused with no way of changing it is problematic.
It would be great to backport this to 5.5.x as well, as currently we have to maintain a fork of Gravity.
```
See also https://community.gravitational.com/t/port-usage-and-verification/163/3
=> Remove port range check for 30000-32767 from checks

lib/install/install.go, lib/process/profile.go
This fixes another regression I only noticed when I retested interactive installer.
The regression crept in after I changed the service behavior w.r.t interruption - it used to be killed by the system previously hence I did not notice the problem originally. But after I made the service handle the `SIGTERM` signal by shutting down properly, it manifested itself.
=> Shutdown wizard process first in stop to unblock a possible wait

lib/expand/join.go, lib/install/agent.go, lib/install/config.go, tool/gravity/cli/install.go
Missed it for some reason when working on install refactoring.
Fixes https://github.com/gravitational/gravity.e/issues/4152.
=> Pass cloud provider to agent so it can query cloud metadata.

lib/ops/opsservice/agents_test.go
This fixes the recent failure in the nightly.
=> Fix a flaky test by bumping the timeout

lib/checks/checks.go, lib/localenv/localenv.go, lib/localenv/remoteenv.go, lib/ops/opsservice/uninstall.go, lib/process/process.go, lib/storage/storage.go, lib/update/cluster/builder.go, lib/update/cluster/builder_test.go, lib/users/users.go, tool/gravity/cli/clusterupdate.go, tool/gravity/cli/register.go, tool/tele/cli/register.go
Renamed in help strings of user-exposed commands, errors and log messages.
Note I didn't touch comments/variables.
Refs https://github.com/gravitational/gravity.e/issues/4157.
=> Rename Ops Center to Gravity Hub in user-visible strings.

lib/install/phases/postsystem.go, lib/install/planbuilder.go
Just had an install fail on "rbac" phase with "kube-system namespace not found error".
This PR updates the "wait" phase to wait for this namespace existence as well.
=> Update wait phase for wait for kube-system namespace.

vagrant/ansible/deploy.yaml, vagrant/ansible/install.yaml
The token length should be greater than 6 characters. This PR fixes the token length in vagrant deployment scripts (dev env).
=> Fix invalid token length in vagrant deployment scripts

assets/site-app/resources/site.yaml, lib/report/k8s.go
Fix a couple of things discovered when helping a customer recently.
* Reduce liveness probe delay on gravity-site to 2 minutes. Closes https://github.com/gravitational/gravity.e/issues/4154.
* Add logs for terminated containers to debug report. Closes https://github.com/gravitational/gravity.e/issues/4153.
=> Couple of fixes.

Gopkg.lock, lib/constants/constants.go, lib/defaults/defaults.go, lib/devicemapper/configure.go, lib/fsm/format.go, lib/ops/opsservice/update.go, lib/ops/utils.go, lib/state/state.go, lib/status/wait.go, lib/storage/plan.go, lib/storage/storage.go, lib/system/fs.go, lib/system/mount/service.go, lib/system/state/state.go, lib/systemservice/service.go, lib/systemservice/systemd.go, lib/update/cluster/builder.go, lib/update/cluster/builder_test.go, lib/update/cluster/executor.go, lib/update/cluster/phases/docker.go, lib/update/cluster/phases/system.go, lib/update/cluster/plan.go, lib/update/system/system.go, tool/gravity/cli/plan.go, tool/gravity/cli/system.go, vendor/github.com/coreos/go-systemd/unit/deserialize.go, vendor/github.com/coreos/go-systemd/unit/escape.go, vendor/github.com/coreos/go-systemd/unit/option.go, vendor/github.com/coreos/go-systemd/unit/serialize.go
Closes https://github.com/gravitational/gravity.e/issues/4147.
This PR addresses the issue with devicemapper disk/partition not being reused when upgrading to overlay storage driver.
* Upgrade detects if the cluster is using dedicated devicemapper device/partition.
* If it does, an additional upgrade phase runs after old planet stops but the new one hasn't started yet:
* Devicemapper data on the device/partition is destroyed.
* The device/partition is formatted.
* The device/partition is mounted under Docker data directory.
* New Planet is started.
* Rollback performs reverse actions for the steps above.
* Because all the stuff with formatting/mounting device/partition has to happen before new Planet starts, I've updated the "system-upgrade" phase to upgrade the package but do not start …
=> [5.5] Reuse devicemapper device for overlay.

lib/localenv/teleport.go, lib/ops/events/events.go, lib/ops/opsservice/operationgroup.go, lib/update/updater.go, tool/gravity/cli/update.go
This PR fixes a couple of issues with audit events for the upgrade operation:
1. These events were missing "user" field.
2. The "upgrade.completed" event was always failing to emit.
Both of these issues were a result of the upgrade using "local" cluster operator. This PR instead makes sure events are emitted using cluster operator client which fixes both issues. Closes https://github.com/gravitational/gravity.e/issues/4162.
=> Fix update operation audit events.

lib/app/hooks/configure.go, lib/app/service/app.go, lib/app/service/manifest.go, lib/app/service/manifest_test.go, lib/app/service/resources_test.go, lib/app/service/test/builder.go, lib/app/suite/suite.go, lib/archive/archive.go, lib/rpc/server/suite_test.go, tool/gravity/cli/app.go
In #452, if the application resource directory itself contains a `resources` sub-directory, hook init containers fail.
To fix this, this PR changes the semantics of `app unpack` sub-command to unpack application resources from the tarball's `resources` directory directly into the specified directory without the `resources` directory itself. This should be a safe (and sensible!) change as the hook's init container code is the only client of `app unpack`.
Fixes #452.
=> [5.5] unpack application resources without the 'resources' directory

tool/gravity/cli/register.go, tool/gravity/main.go, tool/tele/cli/register.go, tool/tele/main.go
This PR brushes up help strings for all user-visible commands and their arguments/flags, both `gravity` and `tele`. Here's the gist of the changes made:
* Make sure "application image" and "cluster image" are used consistently everywhere instead of obsolete terms like "installer", "application", "bundle" and so on.
* Make sure all help strings are capitalized and end with a dot.
* Brush up grammar on some help strings and make some descriptions clearer.
Closes https://github.com/gravitational/gravity.e/issues/4169.
=> Update help strings for commands and their flags.

lib/constants/constants.go, lib/expand/join.go, lib/fsm/format.go, lib/fsm/fsm.go, lib/install/client/client.go, lib/install/install.go, lib/install/proto/installer.pb.go, lib/install/proto/installer.proto, lib/install/proto/proto.go, lib/install/server/server.go, lib/storage/plan.go, lib/update/updater.go, lib/vacuum/vacuum.go, tool/gravity/cli/clusterconfig.go, tool/gravity/cli/clusterupdate.go, tool/gravity/cli/commands.go, tool/gravity/cli/environ.go, tool/gravity/cli/gc.go, tool/gravity/cli/install.go, tool/gravity/cli/operation.go, tool/gravity/cli/plan.go, tool/gravity/cli/register.go, tool/gravity/cli/run.go, tool/gravity/cli/update.go
This PR adds a new hidden subcommand that sets the specified phase state without executing it which is oftentimes useful when repairing failed upgrades or other operations. Implementation-wise this follows how execute/rollback/complete are implemented due to all the differences in how FSMs for different operations work. The new command looks like this:
```
gravity plan set --phase=/checks --state=completed
```
I've also forward-ported a change to add "short" display format for operation plan from 5.5 which I added while working on the Docker device issue.
Closes https://github.com/gravitational/gravity.e/issues/3215.
=> Add command to set the phase state.

docs/6.x/changelog.md
And forward-port changelogs for all previous 6.x versions which got lost in the new 6.x documentation branch.
Also, I think we should start marking the date when a particular version was released, I found myself looking for this information a few times so I started doing so for 6+ releases. You can look up the tag date, but here it is more convenient (for us and customers too).
=> Add 6.0.1 notes.

assets/site-app/resources/monitoring.yaml
Fixes permissions for `gravity resource create/rm` for smtp and alert resources.
=> [5.5] Update gravity-site RBAC in monitoring namespace.

lib/checks/checks.go
Backport https://github.com/gravitational/gravity/pull/471.
=> [5.6.x] backport removal of kubernetes port range from checks

lib/checks/checks.go
Backport https://github.com/gravitational/gravity/pull/471.
=> [5.5.x] backport removal of kubernetes port range from checks

docs/6.x/changelog.md
(CVE-2019-11247, CVE-2019-11249)
Initial draft of release notes for upstream kubernetes CVE's and bumped gravity releases.
=> [DOCS] release notes for 6.1.1, 6.0.2, 5.6.6, 5.5.15 

lib/status/status.go, tool/gravity/cli/status.go
A few minor things:
* Failure to collect alerts does not lead to gravity status failure.
* Make sure alerts section is only displayed if there are active alerts.
* Rename "application" to "cluster image".
=> A few gravity status tweaks.

lib/app/hooks/configure.go, lib/constants/constants.go, lib/install/config.go, lib/install/fsmspec.go, lib/install/phases/constants.go, lib/install/phases/resources.go, lib/install/plan.go, lib/install/plan_test.go, lib/install/planbuilder.go, lib/ops/kubernetes.go, lib/ops/ops.go, lib/ops/opsservice/service.go, lib/ops/opsservice/site.go, lib/ops/site.go, lib/storage/plan.go, lib/storage/storage.go, lib/update/cluster/executor.go, lib/update/cluster/phases/init.go
This pull request makes sure that all hook containers receive environment variables with certain basic cluster information which people keep asking about. The variables which are currently available in hooks are cluster name, cluster provider and initial flavor name.
The way it works is a new config map (I called it `cluster-info`) is created during initial cluster installation (or during upgrade for older clusters) which then gets mounted into hook containers as environment.
This approach is more flexible and extensible than just injecting env vars directly and also helps with separation of concerns because "app service" (the one that creates hooks) doesn't know anything about the cluster.
I will update the documentation in another PR. Closes …
=> Additional hook variables.

lib/app/hooks/configure.go, lib/app/service/app.go
Instead of mounting config map with cluster info into hooks (which won't work if the hook is launched from any namespace other than kube-system), read vars from it and populate environment in the request.
=> Fix hook vars.

docs/6.x/requirements.md
Add RHEL 7.7 and 8.0 to the list of supported distros.
* 7.7 was released last week and I've verified install works with 5.5.15, 6.0.2 and 6.1.1.
* 8.0 was actually added a while ago but is missing from this page so I'm adding it too.
=> Update supported distros list.

build.assets/Makefile, lib/process/teleport.go
The fact that it's set to cluster name messes up Kubernetes integration b/c cluster name can be not resolvable.
=> [6.0] Do not set auth gateway public addrs initially.

lib/rpc/proxy/proxy.go, lib/rpc/proxy/proxy_test.go
This PR attempts to fix an issue with flaky rpc/proxy tests observed in robotest.
It adds explicit `io.Closer` implementation for the proxy local link and moves to use `sync.WaitGroup` instead of channels to observe lifespan of internal connection handlers.
=> Fix flaky rpc/proxy test

build.assets/Makefile, lib/process/teleport.go
https://github.com/gravitational/gravity/pull/589 port to 6.1.
=> [6.1] Do not set auth gateway public addrs.

build.assets/Makefile
Revert changes to `ln` for build on `darwin` due to command line incompatibility
=> [5.5.x] fix build on darwin

lib/app/hooks/configure.go, lib/app/service/app.go, lib/constants/constants.go, lib/install/config.go, lib/install/fsmspec.go, lib/install/phases/constants.go, lib/install/phases/resources.go, lib/install/plan.go, lib/install/plan_test.go, lib/install/planbuilder.go, lib/ops/kubernetes.go, lib/ops/ops.go, lib/ops/opsservice/service.go, lib/ops/opsservice/site.go, lib/ops/site.go, lib/storage/storage.go, lib/update/cluster/executor.go, lib/update/cluster/phases/init.go
Reopening backports of https://github.com/gravitational/gravity/pull/575 and https://github.com/gravitational/gravity/pull/582 to 6.0.
=> [6.0] Hook variables.

lib/app/hooks/configure.go, lib/app/service/app.go, lib/constants/constants.go, lib/install/config.go, lib/install/fsmspec.go, lib/install/phases/constants.go, lib/install/phases/resources.go, lib/install/plan.go, lib/install/plan_test.go, lib/install/planbuilder.go, lib/ops/kubernetes.go, lib/ops/ops.go, lib/ops/opsservice/service.go, lib/ops/opsservice/site.go, lib/ops/site.go, lib/storage/storage.go, lib/update/cluster/executor.go, lib/update/cluster/phases/init.go
Reopening backports of https://github.com/gravitational/gravity/pull/575 and https://github.com/gravitational/gravity/pull/582 to 6.1.
=> [6.1] Hook variables.

lib/ops/operatoracl.go, lib/ops/ops.go, lib/ops/opsservice/configure.go, lib/ops/opsservice/systemupdate.go, lib/ops/opsservice/update.go, lib/update/phase_init.go, tool/gravity/cli/commands.go, tool/gravity/cli/register.go, tool/gravity/cli/run.go, tool/gravity/cli/update.go
Add `gravity update rotate-secrets` symmetrical to `gravity update rotate-{planet,teleport}-config` for use in intermediate upgrades.
=> [5/2.x] add offline rotation of secrets for intermediate upgrades

Makefile, docs/6.x/cluster.md, docs/6.x/faq.md, docs/6.x/pack.md, lib/localenv/localenv.go, lib/ops/opsservice/configure.go, lib/schema/manifest.go, lib/schema/schema.go, tool/gravity/cli/clusterupdate.go, tool/gravity/cli/ops.go
This PR adds an additional boolean manifest field `systemOptions.allowPrivileged` that enables privileged containers in the cluster. Requires https://github.com/gravitational/planet/pull/476. Closes https://github.com/gravitational/gravity/issues/619.
=> Add ability to allow privileged containers via a manifest flag.

terraform-dev/install.yaml
We especially mount disk into /tmp directory to provide enough space for installer
=> Use /tmp folder for gravity installer

lib/install/phases/postsystem.go, lib/install/planbuilder.go
Backport https://github.com/gravitational/gravity/pull/493 to 5.5. Turns out I fixed this issue a couple of months ago but it didn't make it into 5.5.
Closes https://github.com/gravitational/gravity.e/issues/4207.
=> (5.5) Wait for kube-system namespace.

lib/app/dependency.go, lib/app/pull.go, lib/builder/syncer.go
* Enable parallel pull for application packages.
* Update package conflict handling during pulls to avoid introducing inflexible control attributes (`SkipIfExists`). This also reverts the application pull logic behavior.
=> [5.5.x] package dependency/pull updates

lib/schema/schema.go
Put it in the incorrect place in the schema when backporting.
=> (6.0) Fix allowPrivileged flag schema.

lib/schema/schema.go
Put it in the incorrect place when backporting.
=> (6.1) Fix allowPrivileged flag schema.

tool/gravity/cli/update.go
Looks like this logic got lost somehow in-between b/c it's present in 5.2 and 6.0.
=> (5.5) Make sure leader agent runs on current node.

lib/ops/opsservice/plan.go, tool/gravity/cli/update.go
when reporting the package as a result of rotate API - the expectation is that rotating configuration package works from an arbitrary master node and it's not the case for `5.2.x` with binary-based rotation.
=> [5.2.x] translate the teleport configuration package to specific server

build.assets/Dockerfile
The original problem is that the github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/genswagger has been updated a couple of days ago with code only compatible with go1.12 and we `go get -u` it inside the buildbox to build GRPC packages.
Will need to tailor the Makefile to avoid such failures in future by not `go get`ting but this should suffice for now.
=> [5.2.x] bump go to 1.12.9 to fix proto compilation issue

Makefile, lib/update/cluster/phases/etcd.go
=> CVE-2019-11251 (6.1.x)

Makefile, lib/update/cluster/phases/etcd.go
=> CVE-2019-11251 (6.0.x)

Makefile, lib/update/cluster/phases/etcd.go
=> CVE-2019-11251 (5.6.x)

Makefile, lib/update/cluster/phases/etcd.go
=>  CVE-2019-11251 (5.5.x)

Makefile, lib/update/cluster/phases/etcd.go
=> CVE-2019-11251 (master)

lib/system/caps_linux.go, lib/system/mount/mount.go, tool/gravity/cli/journal.go
This fixes an issue with planet journal capture in `gravity system report` resulting in:
```
No journal files were opened due to insufficient permissions.
```
=> [5.5.x] do not drop CAP_DAC_OVERRIDE to be able to access journal files

lib/loc/loc.go, lib/process/import.go
Otherwise it is possible that the state import uses the "wrong" configuration package (and it does fail now that the teleport configuration format has been updated in one of the recent PRs).
=> [5.2.x] select teleport configuration package compatible with the branch

Makefile, assets/site-app/resources/site.yaml, build.assets/Makefile, lib/constants/constants.go, lib/defaults/defaults.go, lib/ops/ops.go, lib/ops/opsservice/configure.go, lib/ops/opsservice/packages.go, lib/ops/opsservice/plan.go, lib/ops/opsservice/shrink.go, lib/ops/opsservice/update.go, lib/pack/utils.go, lib/process/import.go, lib/process/process.go, lib/rpc/server/peers.go, lib/update/cluster/phases/bootstrap.go, lib/update/cluster/steps.go
This PR updates the naming scheme for teleport configuration packages to match planet config/secrets package naming in that the package version equals to that of the bundled package (`teleport` or `planet`) and all config updates are performed by issuing increments in semver metadata.
Updates https://github.com/gravitational/gravity.e/issues/4219.
=> [5.5.x] teleport configuration naming changes

lib/builder/builder.go, lib/localenv/credentials/credentials.go, lib/localenv/localenv.go, lib/localenv/localenv_test.go, lib/localenv/tarballenv.go, tool/tele/cli/build.go, tool/tele/cli/commands.go, tool/tele/cli/register.go, tool/tele/cli/run.go
Supporting changes for https://github.com/gravitational/gravity.e/pull/4220.
This PR extends CredentialsService to support "static" credentials - i.e. a preconfigured credentials entry, for example set on the CLI. This is needed for ability to provide credentials to tele commands in the enterprise version, see PR linked above.
Refs https://github.com/gravitational/gravity.e/issues/4198.
=> Add ability for tele to accept credentials on CLI.

lib/install/dispatcher/buffered/dispatcher.go, lib/install/engine/interactive/wizard.go, lib/install/install.go, lib/install/utils.go, lib/rpc/server/agent_group.go, lib/rpc/server/peer.go, lib/rpc/server/peers.go, lib/utils/error.go, tool/gravity/cli/config.go, tool/gravity/cli/install.go, tool/gravity/main.go
* Fix a couple of typos.
* Return precondition failed errors for initialization failures in service for better visibility in client.
* Return all error context upon operation failure to the client.
Updates https://github.com/gravitational/gravity.e/issues/4205.
Requires https://github.com/gravitational/gravity.e/pull/4226.
=> [6.1.x] Provide all error context upon operation failure

docs/6.x/config.md
It looks like role is an enterprise only resource, but was missing in the docs as Enterprise only.
https://community.gravitational.com/t/unable-to-create-roles-with-6-x/378
=> Mark Role as Enterprise Only

lib/install/flow.go, lib/ops/opsservice/agents.go, lib/rpc/proto/utils.go, lib/rpc/server/agent.go, lib/storage/storage.go, lib/storage/systeminfo.go, lib/update/engine.go, lib/update/updater.go
* Do not count a peer re-sending the join request as a new node.
* Use specific formatting implementation instead of generic dump based on spew for readability.
Updates https://github.com/gravitational/gravity.e/issues/4227.
=> [5.5.x] fix node mismatch when using encrypted installer

Makefile, build.assets/robotest_run_suite.sh, lib/defaults/defaults.go, lib/ops/operatoracl.go, lib/ops/ops.go, lib/ops/opsservice/configure.go, lib/ops/opsservice/packages.go, lib/ops/opsservice/plan.go, lib/ops/opsservice/shrink.go, lib/ops/opsservice/update.go, lib/process/import.go, lib/process/process.go, lib/storage/plan.go, lib/update/cluster/phases/bootstrap.go, lib/update/cluster/phases/coredns.go, lib/update/cluster/phases/init.go, lib/update/cluster/phases/system.go, lib/update/cluster/plan.go, lib/update/clusterconfig/phases/update.go, lib/update/environ/phases/update.go, lib/update/system/system.go, tool/gravity/cli/update.go
This forward-ports enough to fix the upgrades but not the entirety of changes to support intermediate upgrades.
Updates https://github.com/gravitational/gravity.e/issues/4230.
=> [6.1.x] Sync up with 5.5.x to fix update w.r.t package versioning

Gopkg.lock, Gopkg.toml, vendor/github.com/docker/docker/pkg/archive/archive.go, vendor/github.com/gravitational/trace/httplib.go
Update docker from a fork to fix a data race until the bugix has been released officially.
Related [issue](https://github.com/moby/moby/issues/39859) on moby issue tracker and the corresponding upstream [PR](https://github.com/moby/moby/pull/39860).
=> [6.1.x] use docker from a fork to fix a data race

lib/systeminfo/systeminfo.go
Skip entries if target directory does not exist when computing filesystem usage.
Requires forward port to 6.x, master.
Updates https://github.com/gravitational/gravity.e/issues/4232.
=> [5.5.x] do not consider non-existent directories for file system usage stats

lib/report/report.go, lib/report/system.go, lib/utils/exec.go
* Use unprivileged user to collect world-readable parts of /etc.
* Collect log files from the local (working) directory.
Requires forward port.
=> [5.5.x] debug report update

Gopkg.lock, Gopkg.toml, vendor/github.com/gravitational/teleport/lib/auth/auth.go, vendor/github.com/gravitational/teleport/lib/auth/auth_with_roles.go
This PR revendors teleport to fix a regression with creating web sessions in gravity.
Several bugs surfaced on gravity side as a result of this regression:
* UI giving "user not found" error after choosing password for a new user (see linked issue).
* Web installer UI not working (always giving login page).
* Session disconnects when accessing cluster terminal via hub.
Refs https://github.com/gravitational/gravity/issues/757.
=> (6.2) Update teleport to fix issue with web sessions.

lib/defaults/defaults.go, lib/expand/join.go, lib/rpc/server/peer.go, lib/utils/env.go, lib/utils/logging.go, tool/gravity/main.go
* Make agent connect timeout configurable via environment (`GRAVITY_AGENT_CONNECT_TIMEOUT`).
* Ignore deadline exceeded errors when validating connection. As the original motivation for validating the connection to the peer (server) has been early detecting of terminal conditions, connection timeout should not be considered a terminal condition and the agent should be allowed to continue even if connection takes longer than the originally allotted time.
Requires https://github.com/gravitational/gravity.e/pull/4235.
Updates https://github.com/gravitational/gravity.e/issues/4229.
=> [5.5.x] do not treat context expiration as terminal when validating agent connection

Makefile, build.assets/robotest_run_suite.sh, lib/defaults/defaults.go, lib/ops/operatoracl.go, lib/ops/ops.go, lib/ops/opsservice/configure.go, lib/ops/opsservice/packages.go, lib/ops/opsservice/plan.go, lib/ops/opsservice/shrink.go, lib/ops/opsservice/update.go, lib/process/import.go, lib/process/process.go, lib/process/process_test.go, lib/storage/plan.go, lib/update/cluster/phases/bootstrap.go, lib/update/cluster/phases/coredns.go, lib/update/cluster/phases/init.go, lib/update/cluster/phases/system.go, lib/update/cluster/plan.go, lib/update/clusterconfig/phases/update.go, lib/update/environ/phases/update.go, lib/update/system/system.go, tool/gravity/cli/update.go
* Bring branch up-to-date with 6.1.x w.r.t updates
* Sync up with 6.1.x w.r.t to planet/teleport configuration package naming changes to fix the upgrades.
* Bump version of the base application for upgrade tests to 6.1.6 to exercise the issue
Updates https://github.com/gravitational/gravity.e/issues/4230.
=> Sync up with 6.1.x to fix update w.r.t package versioning

Makefile, build.assets/robotest_run_suite.sh, lib/defaults/defaults.go, lib/ops/operatoracl.go, lib/ops/ops.go, lib/ops/opsservice/configure.go, lib/ops/opsservice/packages.go, lib/ops/opsservice/plan.go, lib/ops/opsservice/shrink.go, lib/ops/opsservice/update.go, lib/process/import.go, lib/process/process.go, lib/process/process_test.go, lib/rpc/proxy/proxy.go, lib/rpc/proxy/proxy_test.go, lib/storage/plan.go, lib/update/cluster/phases/bootstrap.go, lib/update/cluster/phases/coredns.go, lib/update/cluster/phases/init.go, lib/update/cluster/phases/system.go, lib/update/cluster/plan.go, lib/update/clusterconfig/phases/update.go, lib/update/environ/phases/update.go, lib/update/system/system.go, tool/gravity/cli/update.go
* Bring branch up-to-date with 6.1.x w.r.t updates
* Sync up with 6.1.x w.r.t to planet/teleport configuration package naming changes to fix the upgrades.
* Bump version of the base application for upgrade tests to 6.1.6 to exercise the issue
Updates https://github.com/gravitational/gravity.e/issues/4230.
=> [6.2.x] Sync up with 6.1.x to fix update w.r.t package versioning

tool/gravity/cli/config.go, tool/gravity/cli/install.go
This change codifies a workaround previously placed in the cloud-init config when creating a cluster via terraform on AWS.
The AWS autojoin integrations use AWS SSM to store the URL of the cluster and token used for joining the cluster by name. When a cluster is uninstalled and being re-installed, new parameters may not have replaced the old ones yet, causing nodes to attempt to join the stale cluster which will fail. The workaround in the bash script operated by testing that the URL in SSM is a valid cluster, and then only launching autojoin once this succeeded. 
I don't see a better way to do this, so I've essentially copied the same logic here, when retrieving the parameters from SSM, test them for validity by trying to connect to the URL and seeing if a successfully http result comes …
=> autojoin stale retry loop

build.assets/robotest_run_suite.sh, lib/process/import.go, lib/process/process_test.go, lib/rpc/proxy/proxy.go, lib/rpc/proxy/proxy_test.go, lib/update/cluster/phases/bootstrap.go
* Fix teleport config fetching code (lib/process/import.go) to support fetching of legacy teleport config packages if no packages are using new versioning scheme.
* Add tests for the added functionality.
* Bonus: fix flaky lib/rpc/proxy test by backporting changes from master.
Updates https://github.com/gravitational/gravity/pull/768 to fix an issue with upgrades over a version that does not use the new configuration package versioning scheme.
=> [6.1.x] followup to #768

Makefile
Upstream Notes: https://github.com/kubernetes/kubernetes/issues/83253
=> bump kubernetes for cve-2019-11253

lib/process/import.go, lib/process/process_test.go
This fixes the `latest package not found` when `gravity-site` is starting up after an upgrade.
=> Backport https://github.com/gravitational/gravity/pull/802.

docs/6.x/changelog.md
Note: I marked 5.6.x as obsolete as I think it's far past our support for a non LTS release.
=> release notes for cve-2019-11253

Jenkinsfile, Jenkinsfile.nightly, build.assets/robotest_run_nightly.sh
Update nightly script to test intermediate upgrades.
I'll be adding the individual branches to the nightly pipeline.
=> [5.5.x] update nightly robotest script to test intermediate upgrades

lib/ops/opsservice/configure.go
add kubernetes service SANs to etcd certs so that etcd is reachable from pods inside the cluster
Requires: forward-port
This is a result of the change in etcd 3 to using the etcd gateway. The etcd gateway acts as a L4 proxy to a master, which means the master cert needs SANs for the gateway nodes, which we don't currently support. As an alternative, have clients within pods access etcd via the kubernetes svc, and contact the master etcd servers directly.
I would discourage this mode of operation for most services, which should instead should deploy an etcd cluster within kubernetes, but in the stolon case it historically uses the cluster etcd.
=> pod access to etcd

lib/update/cluster/engine.go, lib/update/engine.go, lib/update/updater.go
Remove explicit calls to `ActivateSite` - these are handled implicitly by cluster state transitions in `CompleteOperation` / `FailOperation`.
=> [6.1.x] remove explicit calls to ActivateSite

docs/6.x/catalog.md, docs/6.x/changelog.md, docs/6.x/config.md
This fixes 404s in the docs, I've also update 6.x docs to refer to Ops Center to be Gravity Hub
=> Fixes 404s in the Docs

lib/fsm/utils.go, lib/update/updater.go, tool/gravity/cli/clusterconfig.go, tool/gravity/cli/clusterupdate.go, tool/gravity/cli/environ.go
Activate cluster in `Updater.Complete` which is used to explicitly finalize the operation.
=> [6.1.x] reset cluster when completing update plan 

terraform-dev/Makefile, terraform-dev/cloudinit.cfg, terraform-dev/cluster.tf, terraform-dev/install.yaml
Moves clound config into template file. Use one big disk instead of
adding another one for /var/lib/gravity.
=> [5.5] Support nodes_count variable.

lib/localenv/detect.go, tool/gravity/cli/checks.go
@a-palchikov @knisbet Take a look. Based on our discussions in https://github.com/gravitational/gravity/pull/845 I've implemented a bit more intelligent way of detecting the cluster. In addition to installed/not installed it now also recognizes the "partial state" or "degraded state" and recommends the user to figure it out first. Refs https://github.com/gravitational/gravity/issues/840.
=> (5.5) Better cluster detection mechanism.

docs/6.x/changelog.md
6.1.12 marks the first LTS release of the 6.1.x line.
=> 6.1.12 LTS changelog.

tool/gravity/cli/run.go, tool/gravity/cli/status.go
A couple of minor cli tweaks:
* Print cluster name on a separate line in gravity status. Before, it was sort of hidden in the middle of the "cluster nodes" line and people couldn't find it.
* Add root check for "leave" and "remove" command. I actually think it fixes https://github.com/gravitational/gravity/issues/614 as the behavior before was that if you run leave command without sudo but with --force, it would suppress the "root required" error and proceed to system uninstall which would fail some steps that require root leading to this weird systemd unit state.
Should be easy enough to backport to 6.x/5.5 as well.
Closes https://github.com/gravitational/gravity/issues/666 😈
=> Couple gravity cli tweaks.

Gopkg.lock, Gopkg.toml, lib/app/resources/decode.go, lib/app/resources/resourcefiles.go, lib/app/service/vendor.go, lib/builder/build.go, lib/helm/helm.go, lib/system/fs_test.go, lib/utils/progress.go, tool/tele/cli/build.go, tool/tele/cli/commands.go, tool/tele/cli/register.go, tool/tele/cli/run.go, vendor/github.com/gravitational/trace/httplib.go, vendor/github.com/gravitational/trace/trace.go
A few UX improvements to tele build:
* Fix the confusing `unrecognized object: apiVersion=/, kind=` error which was due to empty resource files which our decoder didn't ignore and returned empty resources instead.
* Do not print "unrecognized resource" warning for each resource in tele build output, they can accumulate, pollute the output and confuse the user. Instead, log them and print a single warning to tell them to look in the logs if needed.
* Get rid of the steps in the tele build output which always got out of sync. Instead, use our standard progress output with timestamps.
* Add more context to resource parsing errors. Previously, it would just print a generic "json parse error" with no way of telling which resource file it's for. Now it prints the name of the file with the …
=> tele build UX updates.

lib/blob/cluster/cluster_test.go
This picks up two dropped test errors in `lib/blob/cluster`.
=> lib/blob/cluster: fix dropped test errors in RCPSuite.SetUpTest()

lib/app/service/vendor.go, lib/app/service/vendor_test.go, tool/tele/cli/commands.go, tool/tele/cli/register.go, tool/tele/cli/run.go
Add ability to override Helm values during tele build via `--set` and `--values` flags - flag names are the same as in helm commands and gravity app commands. Closes https://github.com/gravitational/gravity/issues/903.
Should be pretty easy to backport to 6.x as well.
=> Add ability to provide helm values to tele build.

lib/blob/suite/suite.go
This picks up a a dropped error variable in `lib/blob/suite`.
=> lib/blob/suite: fix dropped error

assets/site-app/resources/site.yaml, lib/constants/constants.go
Expose `3026` in gravity-site. Requires https://github.com/gravitational/gravity.e/pull/4258. Refs https://github.com/gravitational/gravity/issues/908.
=> (6.1) Export kubeproxy port.

lib/schema/v1/manifest.go, lib/storage/plan.go, lib/systemservice/service.go
This PR picks up three spots where JSON tags were ineffectual in using `omitempty`.
=> Three omitempty Fixes

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Resolves #923 by adding the code of conduct, and takes a stab at contribution guidelines. CONTRIBUTING felt appropriate to give discoverability to this info from the README.
Testing Done:
```
View these three files in my branch:
https://github.com/wadells/gravity/tree/code-of-conduct#contributing
https://github.com/wadells/gravity/blob/code-of-conduct/CONTRIBUTING.md
https://github.com/wadells/gravity/blob/code-of-conduct/CODE_OF_CONDUCT.md
Double checked that the links work.
```
=> Add CONTRIBUTING.md & CODE_OF_CONDUCT.md

lib/install/engine/cli/cli.go
Fix relative path for `gravity join command`.
Previously it was referring to `gravity` but that's not in PATH (yet) so the join command must be `./gravity` instead.
=> Fix relative path for `gravity join command`

lib/report/system.go, lib/storage/keyval/etcd.go, lib/utils/error.go
* Consider 'leader changed' a transient error and retry accordingly.
* Remove the message collector as it is not working as expected (comes up empty while the logs are no longer stored where it expects them to be).
Fixes https://github.com/gravitational/gravity/issues/947.
=> Consider 'leader changed' a transient error

lib/constants/constants.go, lib/ops/opsservice/endpoints.go
When retrieving endpoints, make a single API call to get services across all namespaces rather than iterating over namespaces.
Closes https://github.com/gravitational/gravity/issues/944. Needs port to 6.2 and master.
=> (6.1) More efficient app endpoints retrieval.

Makefile
Closes https://github.com/gravitational/gravity/issues/945. Requires https://github.com/gravitational/planet/pull/537.
=> Upgrade to Kubernetes 1.17.0.

lib/users/usersservice/usersservice_test.go
This picks off a dropped test error in `lib/users/usersservice`.
=> lib/users/usersservice: pick up dropped error in SetUpTest()

lib/ops/opsservice/configure.go
Fixes a security issue where:
- master nodes re-use the same secret for a majority of certificates. Now only private keys that are required to be the same are maintained.
- Each certificate assigned to a particular node reuses the same private key. Now a private key is generated for each issued certificate.
- Rotation did not rotate private keys. Note: rotation of the root key or apiserver key is not yet supported.
=> generate separate keys for each certificate

docs/6.x/faq.md, docs/6.x/pack.md, lib/app/app.go, lib/app/hooks/configure.go, lib/app/hooks/constants.go, lib/app/hooks/hooks.go, lib/app/service/app.go, lib/app/service/installer.go, lib/install/config.go, lib/install/engine/cli/cli.go, lib/install/phases/app.go, lib/install/planbuilder.go, lib/ops/ops.go, lib/ops/opsservice/update.go, lib/storage/plan.go, lib/storage/storage.go, lib/update/cluster/builder.go, lib/update/cluster/phases/app.go, tool/gravity/cli/clusterupdate.go, tool/gravity/cli/commands.go, tool/gravity/cli/config.go, tool/gravity/cli/register.go, tool/gravity/cli/run.go
Add `--values` and `--set` flags to the install/upgrade commands so users can pass Helm values at install/upgrade time. The provided values are merged into a single values file and mounted into hooks under `/var/lib/gravity/helm/values.yaml` (chose directory other than "resources" to avoid collisions with people's resources) where hooks can use it from. See included docs for more info.
Closes https://github.com/gravitational/gravity/issues/660 (the CLI part, anyway).
=> Add support for Helm values to install/upgrade

docs/6.x/cluster.md, lib/defaults/defaults.go, lib/docker/api.go, lib/docker/imageservice.go, tool/gravity/cli/commands.go, tool/gravity/cli/register.go, tool/gravity/cli/registry.go, tool/gravity/cli/run.go
Add a convenience `gravity registry list` command that displays images published in the cluster registry. Closes https://github.com/gravitational/gravity/issues/696.
=> Add gravity registry list command.

lib/install/fsm.go
Use `gravity install --phase=` to step through the plan b/c `gravity plan` commands are not extended with enterprise fsm yet (see https://github.com/gravitational/gravity/issues/989). This should fix the install in the meanwhile.
=> Use install command to execute phase.

lib/catalog/lister.go, lib/defaults/defaults.go, lib/modules/modules.go, tool/tele/cli/pull.go
Print name of the hub the user is currently logged into for all tele pull/push/ls commands. Requires https://github.com/gravitational/gravity.e/pull/4266. Closes https://github.com/gravitational/gravity/issues/702, closes https://github.com/gravitational/gravity.e/issues/3471.
=> Print active hub for tele commands.

README.md
Found a 404 in the Gravity README and replaced it with a link to Breezy.
=> Fix broken careers link

lib/expand/plan_test.go
This fixes a dropped test error in `lib/expand`.
=> lib/expand: fix dropped test error

tool/gravity/cli/install.go
This picks up a dropped error in `tool/gravity/cli`.
=> tool/gravity/cli: fix dropped error

lib/install/phases/bootstrap.go
This is an attempt to fix the bad teleport log directory permissions issue (https://github.com/gravitational/gravity/issues/1009) which prevents gravity-site from starting up. This happens inconsistently when a customer rotates master nodes.
Full disclosure: I wasn't able to figure out exactly what and when creates `/var/lib/gravity/site/teleport/log` as root but looking at the system where this happened, it is not gravity-site itself b/c when gravity-site initializes it, it does it with correct permissions.
This fix explicitly creates the directory during the bootstrap phase with proper permissions which should alleviate the issue. Closes https://github.com/gravitational/gravity/issues/1009.
=> (6.3) Explicitly create teleport log dir during bootstrap phase.

lib/users/suite/userssuite.go
This picks up two dropped errors in `lib/users/suite`.
=> lib/users/suite: fix dropped errors

lib/terraform/provider/resource_gravity_cluster_auth_preference.go
This picks up a dropped error in `lib/terraform/provider`.
=> lib/terraform/provider: fix dropped error

lib/install/phases/bootstrap.go
https://github.com/gravitational/gravity/pull/1024 forward-port.
=> Explicitly create teleport log dir during bootstrap phase.

tool/gravity/cli/system.go
I think I added this piece of logic when working on the "reusing devicemapper devices for overlay" feature a few months back but I can't recall what my motivation behind that was exactly, but as it turns out it makes it for a very annoying uninstall/install cycle b/c all devices mounted under system directory (state dir, etcd data dir) always get unmounted and their data does not get cleaned up.
=> (5.5) Do not unmount devices during system uninstall.

lib/process/proxy.go
This picks up a dropped error in `lib/process`.
=> lib/process: fix dropped error

Gopkg.lock, Gopkg.toml, lib/defaults/defaults.go, lib/ops/opsservice/configure.go, lib/ops/opsservice/site.go, lib/ops/resources/gravity/gravity_test.go, lib/utils/error.go, vendor/github.com/gravitational/trace/errors.go, vendor/github.com/gravitational/trace/httplib.go, vendor/github.com/gravitational/trace/trace.go
Query `RuntimeEnvironment` and `ClusterConfiguration` resources in a loop with a circuit breaker to retry on transient errors.
Fix tests due to changes to gravitational/trace.
Update gravitational/trace for changes to how remote errors are marshaled.
Requires https://github.com/gravitational/gravity.e/pull/4272.
Updates https://github.com/gravitational/gravity/issues/1054.
=> Use retry when quering resources during possible fail-over

lib/defaults/defaults.go, lib/docker/imageservice.go, lib/helm/client.go, lib/utils/parse.go, tool/gravity/cli/commands.go, tool/gravity/cli/helm.go, tool/gravity/cli/register.go, tool/gravity/cli/run.go, tool/gravity/cli/sync.go
This PR implements a few improvements for the "gravity app" set of commands so they play better with external registries. Before, our registry connection code was pretty much tailored to working with registries inside Gravity clusters.
* Add support for basic auth with registries. I used registry provided with OpenShift online to test this.
* Add support for registry prefixes/namespaces, which is also required by OpenShift for example so the images have to be pushed like `<namespace>/debian-tall`.
* More straightforward connection logic - always try to connect to the registry in a secure way, unless `--insecure` flag (or respective configuration parameter) was specified (which is what Docker does as well). I don't think the "insecure" path was actually before so hopefully nothing will …
=> Better support for external registries auth in app catalog.

lib/defaults/defaults.go, lib/system/environ/uninstall.go, lib/systemservice/service.go, lib/systemservice/systemd.go, tool/gravity/cli/commands.go, tool/gravity/cli/register.go, tool/gravity/cli/run.go, tool/gravity/cli/system.go
Add low-level convenience commands to work with gravity-specific systemd services:
```sh
$ gravity system service stop planet
$ gravity system service start teleport
$ gravity system service journal planet -r
```
Note, that `planet` / `teleport` in the examples above is a pattern - not a service name. It is matched against a list of (possibly active - depending on the action) package services. It ensures that the pattern is unique - otherwise an error is given.
`system service journal` also accepts an arbitrary list of `journalctl` options (`-r` in this example).
A full package locator (albeit less convenient) is also accepted:
```sh
gravity system service stop gravity__gravitational.io__planet__6.1.14-11505-30-g9d0ccde.service
```
Needs forward port to master.
=> [6.1.x] convenience commands for gravity-specific services

docs/6.x/catalog.md
The helm chart link referenced no longer exists.  Tele is also only compatible with the 2.X version of the provided helm chart for alpine, not the 3.X.  The link is set to the release-2.0 of alpine that works with Tele.
=> Fix helm chart link

.github/CODEOWNERS
Instead of hardcoding individual users, create team assignments within github teams, and have the code-owners point to the teams that can be updated.
=> update code owners to point to team assignments
